In [2]:
##? not sure what this is ... 
from numpy.core.numeric import True_

import pandas as pd
import numpy as np

##skip import lines because we are in notebook ... so those files with functions are copied above

## this function gives detailed info on NaN values of input df
#from data_clean import perc_null

#these functionas add a date column (x2) and correct mp season format

#from data_fix_dates import game_add_mp_date, bet_add_mp_date,  fix_mp_season 

#these functions assign nhl_names eg 'NYR' to bet, mp, and game; 
# functions use simple dictionaries

#from data_fix_team_names import bet_to_nhl, mp_to_nhl, game_to_nhl

##these are two different functions for assigning game_id to df_betting, based on team, date, H/A
##one uses df_game as look up table ... other uses df_mp_teams as look up table

#from data_bet_add_game_id import mp_to_bet_add_game_id, game_to_bet_add_game_id


##import all the files 

##file paths

Kaggle_path = "/Users/joejohns/data_bootcamp/Final_Project_NHL_prediction/Data/Kaggle_Data_Ellis/"
mp_path = "/Users/joejohns/data_bootcamp/Final_Project_NHL_prediction/Data/Money_Puck_Data/"
betting_path = "/Users/joejohns/data_bootcamp/Final_Project_NHL_prediction/Data/Betting_Data/"

##Kaggle files

df_game = pd.read_csv(Kaggle_path+'game.csv')
df_game_team_stats = pd.read_csv(Kaggle_path+'game_teams_stats.csv')
df_game_skater_stats = pd.read_csv(Kaggle_path+'game_skater_stats.csv')
df_game_goalie_stats = pd.read_csv(Kaggle_path+'game_goalie_stats.csv')

##more subtle Kaggle features:
df_game_scratches = pd.read_csv(Kaggle_path+'game_scratches.csv')
df_game_officials = pd.read_csv(Kaggle_path+'game_officials.csv')
df_team_info = pd.read_csv(Kaggle_path+'team_info.csv')

## grab all the moneypuck data 

df_mp_teams = pd.read_csv(mp_path+'all_teams.csv')


## grab all betting data 
df1 = pd.read_excel(io = betting_path+'nhl odds 2007-08.xlsx')
df2 = pd.read_excel(io = betting_path+'nhl odds 2008-09.xlsx')
df3 = pd.read_excel(io = betting_path+'nhl odds 2009-10.xlsx')
df4 = pd.read_excel(io = betting_path+'nhl odds 2010-11.xlsx')
df5 = pd.read_excel(io = betting_path+'nhl odds 2011-12.xlsx')
df6 = pd.read_excel(io = betting_path+'nhl odds 2012-13.xlsx')
df7 = pd.read_excel(io = betting_path+'nhl odds 2013-14.xlsx')
df8 = pd.read_excel(io = betting_path+'nhl odds 2014-15.xlsx')
df9 = pd.read_excel(io = betting_path+'nhl odds 2015-16.xlsx')
df10 = pd.read_excel(io = betting_path+'nhl odds 2016-17.xlsx')
df11 = pd.read_excel(io = betting_path+'nhl odds 2017-18.xlsx')
df12 = pd.read_excel(io = betting_path+'nhl odds 2018-19.xlsx')
df13 = pd.read_excel(io = betting_path+'nhl odds 2019-20.xlsx')




df1['season'] = 20072008
df2['season'] = 20082009
df3['season'] = 20092010
df4['season'] = 20102011
df5['season'] = 20112012
df6['season'] = 20122013
df7['season'] = 20132014
df8['season'] = 20142015
df9['season'] = 20152016
df10['season'] = 20162017
df11['season'] = 20172018
df12['season'] = 20182019
df13['season'] = 20192020

df_betting = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13])

In [3]:
df_game_officials

           game_id       official_name official_type
0       2016020045        Dan O'Rourke       Referee
1       2016020045       Trevor Hanson       Referee
2       2016020045      Scott Driscoll      Linesman
3       2016020045      Lonnie Cameron      Linesman
4       2017020812  Justin St. Pierre        Referee
...            ...                 ...           ...
105848  2018030417    Kelly Sutherland       Referee
105849  2018030417          Gord Dwyer       Referee
105850  2018030417       Scott Cherrey      Linesman
105851  2018030417      Pierre Racicot      Linesman
105852  2018030417         Derek Amell      Linesman

[105853 rows x 3 columns]

In [9]:
#experiment with joins

X_game_off = df_game_officials.iloc[:8, :].copy()

X_game = df_game.iloc[:3, :].copy()

X_game_team = df_game_team_stats.iloc[2:6,:].copy()

In [10]:
X_game

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
0,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,United Center,/api/v1/venues/null,America/Chicago,-5,CDT
1,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,KeyBank Center,/api/v1/venues/null,America/New_York,-4,EDT
2,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,right,MTS Centre,/api/v1/venues/null,America/Winnipeg,-5,CDT

In [11]:
X_game_off

      game_id       official_name official_type
0  2016020045        Dan O'Rourke       Referee
1  2016020045       Trevor Hanson       Referee
2  2016020045      Scott Driscoll      Linesman
3  2016020045      Lonnie Cameron      Linesman
4  2017020812  Justin St. Pierre        Referee
5  2017020812        Steve Kozari       Referee
6  2017020812       Mark Shewchyk      Linesman
7  2017020812           Kory Nagy      Linesman

In [5]:
X_game_team

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide
2,2017020812,24,away,True,OT,Randy Carlyle,4.0,34.0,16.0,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right
3,2017020812,7,home,False,OT,Phil Housley,3.0,33.0,17.0,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right
4,2015020314,21,away,True,REG,Patrick Roy,4.0,29.0,17.0,9.0,3.0,1.0,45.7,13.0,5.0,20.0,left
5,2015020314,52,home,False,REG,Paul Maurice,1.0,21.0,22.0,11.0,2.0,0.0,54.3,13.0,7.0,9.0,left

In [14]:
X_merge = X_game.merge(X_game_team, on='game_id', how = 'left')

In [15]:
X_merge.iloc[:, :]

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,...,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide
0,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,34.0,16.0,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right
2,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,33.0,17.0,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right
3,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,right,...,29.0,17.0,9.0,3.0,1.0,45.7,13.0,5.0,20.0,left
4,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,right,...,21.0,22.0,11.0,2.0,0.0,54.3,13.0,7.0,9.0,left

In [12]:
X_big_merge = X_game.merge(X_game_team, on = 'game_id', how = 'left').merge(X_game_off, on = 'game_id', how = 'left')

In [13]:
X_big_merge

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,...,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide,official_name,official_type
0,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dan O'Rourke,Referee
1,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trevor Hanson,Referee
2,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scott Driscoll,Linesman
3,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lonnie Cameron,Linesman
4,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right,Justin St. Pierre,Referee
5,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right,Steve Kozari,Referee
6,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right,Mark Shewchyk,Linesman
7,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right,Kory Nagy,Linesman
8,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right,Justin St. Pierre,Referee
9,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right,Steve Kozari,Referee
10,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right,Mark Shewchyk,Linesman
11,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,...,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right,Kory Nagy,Linesman
12,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,right,...,9.0,3.0,1.0,45.7,13.0,5.0,20.0,left,NaN,NaN
13,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,right,...,11.0,2.0,0.0,54.3,13.0,7.0,9.0,left,NaN,NaN

In [ ]:
##stuff not working as well as merge

In [40]:
X_join = X_game.join(X_game_team, on = 'game_id', how = 'outer', lsuffix = 'game', rsuffix ='team')

X_join 

X_concat = pd.concat([X_game_team, X_game], axis = 1)