In [108]:

import pandas as pd
import numpy as np

In [109]:
##bring in Leung data (data is from Leung's Git Repo on betting on nhl 2018); he scraped it from nhl.com


pathjj = '/Users/joejohns/' 
data_path = 'data_bootcamp/GitHub/final_project_nhl_prediction/Data/Leung_Data_Results/nhl_data_Leung.csv'
results_path = 'data_bootcamp/GitHub/final_project_nhl_prediction/Data/Leung_Data_Results/results_Leung.csv'
L_data = pd.read_csv(pathjj+data_path)  #stats CF etc ... one line every data and team so num_dates*30? rows
L_res = pd.read_csv(pathjj+results_path)  #results win, loss etc
#df_data.dropna(inplace = True)

In [110]:
#My old data sets (next two cells)


Kaggle_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/"
mp_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/"
betting_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/"
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/nhl odds 2007-08.xlsx
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/


##Kaggle files

df_game = pd.read_csv(Kaggle_path+'game.csv')
df_game_team_stats = pd.read_csv(Kaggle_path+'game_teams_stats.csv')

df_team_info = pd.read_csv(Kaggle_path+'team_info.csv')

In [111]:
##? not sure what this is ... 
from numpy.core.numeric import True_


##import all the files 

##file paths

Kaggle_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/"
mp_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/"
betting_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/"
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/nhl odds 2007-08.xlsx
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/


##Kaggle files

df_game = pd.read_csv(Kaggle_path+'game.csv')
df_game_team_stats = pd.read_csv(Kaggle_path+'game_teams_stats.csv')
df_game_skater_stats = pd.read_csv(Kaggle_path+'game_skater_stats.csv')
df_game_goalie_stats = pd.read_csv(Kaggle_path+'game_goalie_stats.csv')

##more subtle Kaggle features:
df_game_scratches = pd.read_csv(Kaggle_path+'game_scratches.csv')
df_game_officials = pd.read_csv(Kaggle_path+'game_officials.csv')
df_team_info = pd.read_csv(Kaggle_path+'team_info.csv')

## grab all the moneypuck data 

df_mp_teams = pd.read_csv(mp_path+'all_teams.csv')


## grab all betting data 
df1 = pd.read_excel(io = betting_path+'nhl odds 2007-08.xlsx')
df2 = pd.read_excel(io = betting_path+'nhl odds 2008-09.xlsx')
df3 = pd.read_excel(io = betting_path+'nhl odds 2009-10.xlsx')
df4 = pd.read_excel(io = betting_path+'nhl odds 2010-11.xlsx')
df5 = pd.read_excel(io = betting_path+'nhl odds 2011-12.xlsx')
df6 = pd.read_excel(io = betting_path+'nhl odds 2012-13.xlsx')
df7 = pd.read_excel(io = betting_path+'nhl odds 2013-14.xlsx')
df8 = pd.read_excel(io = betting_path+'nhl odds 2014-15.xlsx')
df9 = pd.read_excel(io = betting_path+'nhl odds 2015-16.xlsx')
df10 = pd.read_excel(io = betting_path+'nhl odds 2016-17.xlsx')
df11 = pd.read_excel(io = betting_path+'nhl odds 2017-18.xlsx')
df12 = pd.read_excel(io = betting_path+'nhl odds 2018-19.xlsx')
df13 = pd.read_excel(io = betting_path+'nhl odds 2019-20.xlsx')




df1['season'] = 20072008
df2['season'] = 20082009
df3['season'] = 20092010
df4['season'] = 20102011
df5['season'] = 20112012
df6['season'] = 20122013
df7['season'] = 20132014
df8['season'] = 20142015
df9['season'] = 20152016
df10['season'] = 20162017
df11['season'] = 20172018
df12['season'] = 20182019
df13['season'] = 20192020

##omit 20072008 
df_betting = pd.concat([df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13])

In [114]:

def fav_pred(x):
    if x < 0:
        return 1
    if x>0:
        return 0
    if x==0:
        print("O odds detected, nan returned")
        return np.NaN
v_fav_pred = np.vectorize(fav_pred)

def implied_proba(odds):
    if odds > 0: 
        return 100/(odds+100)    #bet 100 to get 100+odds; profit = odds
    if odds < 0:
        return (-odds)/(-odds + 100)   #bet |odds| to get 100+|odds|; profit = 100
    
    

df= df_betting.copy()

df

,Date,Rot,VH,Team,1st,2nd,3rd,Final,Open,Close,Open OU,Unnamed: 11,Close OU,Unnamed: 13,season,Puck Line,Unnamed: 15,PuckLine,OpenOU,CloseOU
0,1004,1,V,NYRangers,0,1,1,2,100,-120,5.5,-110,5.5,-105,20082009,NaN,NaN,NaN,NaN,NaN
1,1004,2,H,TampaBay,0,0,1,1,-120,100,5.5,-110,5.5,-115,20082009,NaN,NaN,NaN,NaN,NaN
2,1004,3,V,Pittsburgh,1,1,1,4,-105,-110,6.0,-130,6.0,100,20082009,NaN,NaN,NaN,NaN,NaN
3,1004,4,H,Ottawa,1,2,0,3,-115,-110,6.0,110,6.0,-120,20082009,NaN,NaN,NaN,NaN,NaN
4,1005,51,V,TampaBay,1,0,0,1,105,105,5.5,105,5.5,110,20082009,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2419,925,28,N,Dallas,2,1,1,4,140,135,NaN,-190,NaN,-110,20192020,NaN,110.0,1.5,5.0,5.0
2420,926,29,N,Dallas,1,0,1,3,145,150,NaN,-180,NaN,-110,20192020,NaN,-135.0,1.5,5.0,5.0
2421,926,30,N,TampaBay,0,1,1,2,-166,-165,NaN,160,NaN,-110,20192020,NaN,115.0,-1.5,5.0,5.0
2422,928,1,N,TampaBay,1,1,0,2,-161,-170,NaN,155,NaN,-110,20192020,NaN,-135.0,-1.5,5.0,5.0
2423,928,2,N,Dallas,0,0,0,0,141,155,NaN,-175,NaN,-110,20192020,NaN,115.0,1.5,5.0,5.0

##Note Bene: In L_data or L_res team id wrong! not franchise id either ...

In [5]:
## cleaning tool


def perc_null(X):
    
    total = X.isnull().sum().sort_values(ascending=False)
    data_types = X.dtypes
    percent = (X.isnull().sum()/X.isnull().count()).sort_values(ascending=False)

    missing_data = pd.concat([total, data_types, percent], axis=1, keys=['Total','Type' ,'Percent'])
    return missing_data

In [6]:
##fixing dates and season label 


def to_string(n):
    s = str(n)
    if len(s) ==1:
        return "0"+s
    else:
        return s

#makes mp_date for L_data '2014-1-16' --> 20140116 (integer)
    
def L_to_mp_date(s):
    ymd = s.split('-')
    y = ymd[0]
    m = ymd[1]
    d = ymd[2]
    if len(m) ==1:
        m = '0'+m
    if len(d) == 1:
        d = '0'+d
    return int(y+m+d)

#test '2014-1-16'.split('-')
#make_mp_date('2014-10-16')    
    
    
##for assigning dates in df_game
#takes in date_time date and returns integer yyyymmdd eg 20080904
##note this is df_mp format

def game_add_mp_date(date_time):
    d = date_time.day
    m = date_time.month
    y = date_time.year
    dd = to_string(d)
    mm = to_string(m)
    yyyy = str(y)
    return(int(yyyy+mm+dd))

##test 
date_time1 = pd.to_datetime('2016-10-19T00:30:00Z')
date_time2 = pd.to_datetime('2008-09-19T00:30:00Z')

print("two tests for game_add_mp_date:")
print(game_add_mp_date(date_time1) == 20161019)
print(game_add_mp_date(date_time2)==20080919)
print(" ")
##for assigning dates to df_betting
#takes in ingegers date = 913 or 1026 season = 20082009 
# returns  returns integer yyyymmdd eg 20080904
#note this is df_mp format

def bet_add_mp_date(date, season):
    d = str(date)
    s = str(season)
    if len(d) == 3:
        d = "0"+d 
    if (900 < date):
        y= s[:4]
    else:
        y = s[4:]
    return int(y+d)


##fix season format for df_mp
##takes in integer 2008 and returns 20082009
##note: I have verified in df_mp for two seasons 2008 labels 20082009

def fix_mp_season(n):
    return int(str(n)+str(n+1))

def L_add_season(mp_date):
    st = str(mp_date)
    y = st[0:4]
    ym1 = str(int(y)-1) 
    yp1 =  str(int(y)+1)
    
    m = st[4:6]
    d = st[6:8]
    if 9 <= int(m) <= 12:
        return int(y+yp1)
    if 1 <= int(m) <= 8:
        return int(ym1+y)

##df_game_team_stats does not have 'season' or 'won' so we add that 

def add_season_from_id(game_id):
    id = str(game_id)
    y = int(id[0:4])
    yn = y+1
    return int(str(y)+str(yn))



##test
print("three tests for bed_add_mp_date:")
print(bet_add_mp_date(912, 20082009) == 20080912)
print(bet_add_mp_date(1025,20102011) == 20101025)
print(bet_add_mp_date(227,20102011) == 20110227)
print(" ")

##tests
print("two tests for fix_mp_season:")
print(fix_mp_season(2008) == 20082009)
print(fix_mp_season(2019) == 20192020)
print(" ")

print("three tests for L_add_season:")
print(L_add_season('20140119')==20132014)
print(L_add_season('20140912')==20142015)

    
print(" ")


print("three tests for L_to_mp_season:")
print(L_to_mp_date('2014-10-16')==20141016)
print(L_to_mp_date('2014-1-16')==20140116)
print(L_to_mp_date('2014-1-6')==20140106)
    
print(" ")

print('test for add_season_from_id')
#test 
print(add_season_from_id(2019021081) == 20192020)

two tests for game_add_mp_date:
True
True

three tests for bed_add_mp_date:
True
True
True

two tests for fix_mp_season:
True
True

three tests for L_add_season:
True
True

three tests for L_to_mp_season:
True
True
True

test for add_season_from_id
True

In [7]:
##fix team names
##Leung dropped all the ATL games so I should do same 
# issues CAL MON and WAS

L_to_nhl_dic = {'ANA': 'ANA',
 'ARI': 'ARI',
 'ATL': 'ATL',
 'BOS': 'BOS',
 'BUF': 'BUF',
 'CAR': 'CAR',
 'CBJ': 'CBJ',
 'CAL': 'CGY',
 'CHI': 'CHI',
 'COL': 'COL',
 'DAL': 'DAL',
 'DET': 'DET',
 'EDM': 'EDM',
 'FLA': 'FLA',
 'LAK': 'LAK',
 'MIN': 'MIN',
 'MON': 'MTL',
 'NJD': 'NJD',
 'NSH': 'NSH',
 'NYI': 'NYI',
 'NYR': 'NYR',
 'OTT': 'OTT',
 'PHI': 'PHI',
 'PIT': 'PIT',
 'SJS': 'SJS',
 'STL': 'STL',
 'TBL': 'TBL',
 'TOR': 'TOR',
 'VAN': 'VAN',
 'VGK': 'VGK',
 'WPG': 'WPG',
 'WAS': 'WSH'}


mp_to_nhl_dic = {'ANA': 'ANA',
 'ARI': 'ARI',
 'ATL': 'ATL',
 'BOS': 'BOS',
 'BUF': 'BUF',
 'CAR': 'CAR',
 'CBJ': 'CBJ',
 'CGY': 'CGY',
 'CHI': 'CHI',
 'COL': 'COL',
 'DAL': 'DAL',
 'DET': 'DET',
 'EDM': 'EDM',
 'FLA': 'FLA',
 'L.A': 'LAK',
 'MIN': 'MIN',
 'MTL': 'MTL',
 'N.J': 'NJD',
 'NSH': 'NSH',
 'NYI': 'NYI',
 'NYR': 'NYR',
 'OTT': 'OTT',
 'PHI': 'PHI',
 'PIT': 'PIT',
 'S.J': 'SJS',
 'STL': 'STL',
 'T.B': 'TBL',
 'TOR': 'TOR',
 'VAN': 'VAN',
 'VGK': 'VGK',
 'WPG': 'WPG',
 'WSH': 'WSH'}

bet_to_nhl_dic = {'Anaheim': 'ANA',
 'Arizona': 'ARI',
 'Arizonas': 'ARI',
 'Atlanta': 'ATL',
 'Boston': 'BOS',
 'Buffalo': 'BUF',
 'Calgary': 'CGY',
 'Carolina': 'CAR',
 'Chicago': 'CHI',
 'Colorado': 'COL',
 'Columbus': 'CBJ',
 'Dallas': 'DAL',
 'Detroit': 'DET',
 'Edmonton': 'EDM',
 'Florida': 'FLA',
 'LosAngeles': 'LAK',
 'Minnesota': 'MIN',
 'Montreal': 'MTL',
 'NYIslanders': 'NYI',
 'NYRangers': 'NYR',
 'Nashville': 'NSH',
 'NewJersey': 'NJD',
 'Ottawa': 'OTT',
 'Philadelphia': 'PHI',
 'Phoenix': 'ARI',
 'Pittsburgh': 'PIT',
 'SanJose': 'SJS',
 'St.Louis': 'STL',
 'Tampa': 'TBL',
 'TampaBay': 'TBL',
 'Toronto': 'TOR',
 'Vancouver': 'VAN',
 'Vegas': 'VGK',
 'Washington': 'WSH',
 'Winnipeg': 'WPG',
 'WinnipegJets': 'WPG'}

game_to_nhl_dic = {1: 'NJD',
 4: 'PHI',
 26: 'LAK',
 14: 'TBL',
 6: 'BOS',
 3: 'NYR',
 5: 'PIT',
 17: 'DET',
 28: 'SJS',
 18: 'NSH',
 23: 'VAN',
 16: 'CHI',
 9: 'OTT',
 8: 'MTL',
 30: 'MIN',
 15: 'WSH',
 19: 'STL',
 24: 'ANA',
 27: 'ARI',
 2: 'NYI',
 10: 'TOR',
 13: 'FLA',
 7: 'BUF',
 20: 'CGY',
 21: 'COL',
 25: 'DAL',
 29: 'CBJ',
 52: 'WPG',
 22: 'EDM',
 54: 'VGK',
 12: 'CAR',
 53: 'ARI',
 11: 'ATL'}

def L_to_nhl(abbrevName):
    return L_to_nhl_dic[abbrevName]


def bet_to_nhl(Team):
    return bet_to_nhl_dic[Team]

def mp_to_nhl(team):
    return mp_to_nhl_dic[team]

def game_to_nhl(team_id):
    return game_to_nhl_dic[team_id]

##simple tests:
print(set(bet_to_nhl_dic.values()) == set(mp_to_nhl_dic.values()) )
print(set(bet_to_nhl_dic.values() )== set(game_to_nhl_dic.values()) )
print(set(mp_to_nhl_dic.values()) == set(game_to_nhl_dic.values()) )
print(set(mp_to_nhl_dic.values()) == set(L_to_nhl_dic.values()) )
print(set(game_to_nhl_dic.values()))
print(set(bet_to_nhl_dic.values()))
print(set(mp_to_nhl_dic.values()))
#print(set(mp_to_nhl_dic.values()) == set(L_data['teamAbbreviation'])) #these are different bec no ATL in L_data
len(set(mp_to_nhl_dic.values()))

True
True
True
True
{'BUF', 'CGY', 'DAL', 'COL', 'CHI', 'MTL', 'PIT', 'STL', 'NJD', 'PHI', 'OTT', 'ATL', 'CBJ', 'LAK', 'NYR', 'DET', 'ARI', 'CAR', 'MIN', 'NSH', 'FLA', 'TOR', 'SJS', 'EDM', 'BOS', 'VAN', 'NYI', 'VGK', 'ANA', 'WPG', 'TBL', 'WSH'}
{'CGY', 'DAL', 'COL', 'CHI', 'MTL', 'PIT', 'STL', 'NJD', 'PHI', 'OTT', 'ATL', 'CBJ', 'LAK', 'NYR', 'DET', 'ARI', 'CAR', 'MIN', 'NSH', 'FLA', 'WSH', 'TOR', 'EDM', 'SJS', 'BOS', 'VAN', 'NYI', 'VGK', 'ANA', 'WPG', 'TBL', 'BUF'}
{'CGY', 'DAL', 'COL', 'CHI', 'MTL', 'PIT', 'STL', 'NJD', 'PHI', 'OTT', 'ATL', 'CBJ', 'LAK', 'NYR', 'DET', 'ARI', 'CAR', 'MIN', 'NSH', 'FLA', 'WSH', 'TOR', 'EDM', 'SJS', 'BOS', 'VAN', 'NYI', 'VGK', 'ANA', 'WPG', 'TBL', 'BUF'}

32

In [8]:
##assign game_id to df_betting (two ways)

##these two functions 
# assign game_id to df_betting ... using two different look up tables, df_game and df_mp_teams
##note the following error codes are assigned if a game is not found or found more than once 
# if a home game is empty: 80    #8 is for h
# if a home game has >= 2 entries: 82
# if an away game is empty: 10   #1 is for a
# if an away game has >= 12 entries: 82

#df_betting['mp_game_id'] =  np.vectorize(mp_to_bet_add_game_id, excluded={0})(df_mp_teams, df_betting['mp_date'], df_betting['nhl_name'], df_betting['VH'] ) 


        
def game_to_bet_add_game_id(df_game_team_stats, mp_date, nhl_name, VH):##put VH in there! duh
    if VH == 'H':
        ## this h and (also a) is an array of values ... it  may be empty; we expect exactly one element; might have >=2 or 0  if something is wrong
        h = df_game.loc[(df_game_team_stats['mp_date'] == mp_date)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['HoA'] == 'home'),  :]['game_id'].values
        if len(h) ==1:
            return h[0]
        elif len(h)==0:  #and mp_date < 2010000:
            return 80
            print(mp_date)
        elif len(h) > 1:
            return 82
    if VH == 'V':
        a = df_game.loc[(df_game_team_stats['mp_date'] == mp_date)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['HoA'] == 'away'),  :]['game_id']
        if len(a) ==1:
            return a[0]
        elif len(a)==0:
            return 220
        elif len(a) > 1:
            return 222



def mp_to_bet_add_game_id(df_mp_teams, mp_date, nhl_name, VH):##put VH in there! duh
    if VH == 'H':
        h = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['home_or_away'] == 'HOME'),  :]['game_id'].values
        if len(h) ==1:
            return h[0]
        elif len(h)==0: 
            return 80   
            print(mp_date)
        elif len(h) > 1:
            return 82
    if VH == 'V':
        a = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['home_or_away'] == 'AWAY'),  :]['game_id'].values
        if len(a) ==1:
            return a[0]
        elif len(a)==0:
            return 10   
        elif len(a) > 1:
            return 12

    if VH == 'N':
        n = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name),  :]['game_id'].values
        if len(n) ==1:
            return n[0]
        elif len(n)==0:
            return 130   
        elif len(n) > 1:
            return 132
        
    else:
        return 26
    

def mp_to_bet_add_game_id_no_VH(df_mp_teams, mp_date, nhl_name):##put VH in there! duh
    ha = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name),  :]['game_id'].values
    if len(ha) ==1:
        return ha[0]
    elif len(ha)==0: 
        return 180   
    elif len(ha) > 1:
        return 182
    else:
        return 26

In [9]:
#cleaning up df's before merge ...

df_betting = df_betting.loc[:, ['Date', 'season','VH', 'Team', 'Open']].copy()
df_mp_teams.rename(columns={"teamId": "team_id", 'gameDate': 'mp_date', 'gameId':'game_id' }, inplace = True)
##note there are other column names which differ, but team_id, mp_date, game_id are key for joining so we  
##make it consistent

df_mp_teams_big = df_mp_teams.copy()
##only has the rows for all situations (divide num rows by 5)

#restrict situation to all 
df_mp_teams = df_mp_teams.loc[(df_mp_teams['situation'] == 'all'), :] #&(df_mp_teams['playoffGame']==0), :].copy()

##restrict types to all situations later before merge 

df_game_team_stats.drop_duplicates(inplace = True)
df_game_team_stats = df_game_team_stats[~df_game_team_stats['team_id'].isin([87,88,89,90])].copy()
df_betting = df_betting[~(df_betting['VH'] == 'N')].copy()

In [10]:
##add season and won to df_game_team_stats (need later to re-do part of missing Leung data )

df_game_team_stats['season'] = np.vectorize(add_season_from_id)(df_game_team_stats['game_id']).copy()
df_game_team_stats['won'] = df_game_team_stats['won'].apply(int).copy()

#change 2008 to 20082009 for df_mp_teams

df_mp_teams['season'] = np.vectorize(fix_mp_season)(df_mp_teams['season']).copy()

In [11]:
# fix these in L_data: 'endDate', 'teamAbbreviation'
L_data['mp_date'] = np.vectorize(L_to_mp_date)(L_data['endDate']).copy() 
L_data['nhl_name'] = np.vectorize(L_to_nhl)(L_data['teamAbbreviation']).copy() 

L_data['season'] = np.vectorize(L_add_season)(L_data['mp_date'])
#L_data.columns

In [12]:
##fix some labels in df_betting and df_mp_teams

df_betting['mp_date'] = np.vectorize(bet_add_mp_date)(df_betting['Date'], df_betting['season']).copy()

HA_dic = { 'H': 'home', 'V': 'away', 'HOME': 'home', 'AWAY':'away'}
def add_HoA(h_or_a):  # h_or_a can be either of the formats used by mp or betting
    return HA_dic[h_or_a]

df_betting['HoA'] = df_betting['VH'].apply(add_HoA).copy()

df_mp_teams['HoA'] = df_mp_teams['home_or_away'].apply(add_HoA).copy()




df_betting['nhl_name'] = df_betting['Team'].apply(bet_to_nhl).copy()
df_game_team_stats['nhl_name'] = df_game_team_stats['team_id'].apply(game_to_nhl).copy()
df_mp_teams['nhl_name'] = df_mp_teams['name'].apply(mp_to_nhl).copy()

df_betting['game_id'] =  np.vectorize(mp_to_bet_add_game_id_no_VH, excluded={0})(df_mp_teams, df_betting['mp_date'], df_betting['nhl_name'] ).copy()

In [13]:


##get ready to restrict seasons; I reduced it to 20182019 for Leung
seasons = []
for n in range(2008,2019):
    seasons.append(int(str(n)+str(n+1)))

#check seasons look ok
print(seasons)

[20082009, 20092010, 20102011, 20112012, 20122013, 20132014, 20142015, 20152016, 20162017, 20172018, 20182019]

In [14]:
#restrict seasons 

L_data = L_data.loc[L_data['season'].isin(seasons), :].copy()

df_betting = df_betting.loc[df_betting['season'].isin(seasons), :].copy()
#df_game_team_stats = df_game_team_stats.loc[df_game_team_stats['season'].isin(seasons), :].copy()
df_mp_teams = df_mp_teams.loc[df_mp_teams['season'].isin(seasons), :].copy()
#df_mp_teams = df_mp_teams.loc[df_mp_teams['season'].isin(seasons), :].copy()


## the index is no longer consecutive so we reset:

df_betting.reset_index(drop = True, inplace = True)
#df_game_team_stats.reset_index(drop = True, inplace = True)
df_mp_teams.reset_index(drop = True, inplace = True)
L_data.reset_index(drop = True, inplace = True)


##! restrict df_game_team_stats later using the game_id

df_temp = df_results.dropna(inplace = False).copy()

A = [set(df_betting['game_id']) , set(df_game_team_stats['game_id']) , set(df_results['game_id'])   ] 

for i in range(3):
    j = i + 1 %3   
    print(i, len(A[i])) 
    print(i, j, 'inters: ', len( set.intersection(A[i], A[j]) )
    print("all: ": len( set.intersection(A[0],A[1],A[2]))

In [15]:
##only doing first merge now ... 

common_game_ids = set.intersection( set(df_betting['game_id']) , set(df_game_team_stats['game_id']) ) #, set(df_results['game_id'])   ) 

A = [set(df_betting['game_id']) , set(df_game_team_stats['game_id'])] 

print(len(A[0]))
print(len(A[1]))
print("all: ", len( set.intersection(A[0],A[1]) ))

14064
23730
all:  13887

In [16]:
    
df_betting = df_betting.loc[df_betting['game_id'].isin(common_game_ids), :].copy()
df_game_team_stats = df_game_team_stats.loc[df_game_team_stats['game_id'].isin(common_game_ids), :].copy()
#df_mp_teams = df_mp_teams.loc[df_mp_teams['game_id'].isin(common_game_ids), :].copy()

In [17]:
##check consistency of nhl_names, HoA ...

#df_mp_teams.sort_values(by = ['game_id', 'nhl_name'], inplace = True)
df_game_team_stats.sort_values(by = ['game_id', 'nhl_name'], inplace = True)
df_betting.sort_values(by = ['game_id', 'nhl_name'], inplace = True)

df_betting.reset_index(drop = True, inplace = True)
df_game_team_stats.reset_index(drop = True, inplace = True)
#df_mp_teams.reset_index(drop = True, inplace = True)

In [18]:
##The big merge! Note: I am not using X_merge2 in this note book, but it is important on prev version


X_merge = pd.merge(df_betting, df_game_team_stats, on = ['game_id', 'nhl_name'], how = 'inner', suffixes = ('_bet', '_gm_stats'))

#X_merge2 = pd.merge(X_merge, df_mp_teams, on = ['game_id', 'nhl_name', 'mp_date', 'season'], how = 'inner', suffixes = ('_merge', '_mp_teams'))

#print(2*len(common_game_ids),      X_merge2.shape[0])

In [19]:
#drop ATL because Leung's data did

X_merge = X_merge.loc[ (X_merge['nhl_name'] !='ATL'), :].copy()

X_merge.rename(columns = {'season_bet':'season'}, inplace=True)
X_merge.rename(columns = {'HoA_gm_stats':'HoA'}, inplace=True)
#X_merge_L3 = pd.merge(X_merge, L_data, on = ['nhl_name', 'mp_date', 'season'], how = 'left', suffixes = ('_merge', '_L'))

##using this as 'HoA' results in less data loss

In [20]:
##convenient function for turning Vegas odds (-200 = fav, 120 = underdog) into game predictions  win 1, lose 0
def Vegas_pred(Open):
    if Open < 0:
        return 1 
    elif Open > 0:
        return 0
Vegas_pred(-200)

1

In [21]:
X_merge['Open'].isnull().sum()

0

In [22]:
np.vectorize(Vegas_pred)(np.array([2,-2]))

array([0, 1])

In [23]:
X_merge['Vegas_pred_won'] = X_merge['Open'].apply(Vegas_pred).copy()

In [24]:
X_merge = X_merge.loc[~(X_merge['Open'] == 0), :].copy()

In [25]:
X_merge['won'] = X_merge['won'].apply(int).copy()

In [ ]:
X_merge['won'] = X_merge['won'].apply(int)

In [29]:
X_merge['won'] == X_merge['Vegas_pred_won']

0        1
1        0
2        0
3        1
4        1
        ..
27769    1
27770    1
27771    0
27772    0
27773    1
Name: won, Length: 27526, dtype: int64

In [30]:
##Here we start creating a new df called df_results ... it will have similar form to df_game
##and is suitable fora attaching Leung's data ... (I am not using df_game because I'm scared of it's GMT. dates
##which did work sometimes properly (I got tired of it so never checked super thoroughly)

#From X_merge use the game_id as a seed to make new df in the form of df_game ...(df_game is annoying bc of date)


##these are the games we will use:
list_game_ids = sorted(set(X_merge['game_id']))
print(len(sorted(set(X_merge['game_id']))))

df_results = pd.DataFrame({'game_id':list_game_ids})

13886

In [31]:

###This is adapted from Leung's code.


def value(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 3.14
    else: 
        return frame.iloc[0][key].astype(float)

def intValue(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 314
    else: 
        return int(frame.iloc[0][key])
    
def strValue(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return "314"
    else: 
        return frame.iloc[0][key]
    
def get_home_results(game_id):
    return X_merge.loc[(X_merge['game_id'] == game_id)&(X_merge['HoA'] == 'home'), :]


def get_away_results(game_id):
    return X_merge.loc[(X_merge['game_id'] == game_id)&(X_merge['HoA'] == 'away'), :]

    
def add_results(row):
    home = get_home_results(row['game_id']) #can use home 
    away = get_away_results(row['game_id'])
    
    row['mp_date'] = intValue(home, 'mp_date')
    row['season'] = intValue(home, 'season')
    
    row['home_team'] = strValue(home, 'nhl_name')
    row['away_team'] = strValue(away, 'nhl_name')
    
    
    row['home_odds'] = value(home, 'Open')
    row['away_odds'] = value(away, 'Open')
    
    row['home_goals'] = value(home, 'goals')
    row['away_goals'] = value(away, 'goals')
    
    row['home_win'] = intValue(home, 'won')  #can use home
    row['settled_in'] = strValue(home, 'settled_in')
    
    return row

df_results = df_results.apply(add_results, axis=1).copy()

In [32]:
df_results.shape

(13886, 11)

In [36]:
(df_results =="314").sum()

game_id       0
mp_date       0
season        0
home_team     0
away_team     0
home_odds     0
away_odds     0
home_goals    0
away_goals    0
home_win      0
settled_in    0
dtype: int64

In [33]:
perc_null(df_results)

            Total     Type   Percent
mp_date       123  float64  0.008858
season        123  float64  0.008858
home_team     123   object  0.008858
away_team     123   object  0.008858
home_odds     123  float64  0.008858
away_odds     123  float64  0.008858
home_goals    123  float64  0.008858
away_goals    123  float64  0.008858
home_win      123  float64  0.008858
settled_in    123   object  0.008858
game_id         0  float64  0.000000


###This is adapted from Leung's code.

##Here we taking data from L_data and attaching to our new df_results (one row for each game id in X_merge)
##we do not use X_merge because it has two rows for every game id (H and A)

 
##get results info from X_merge: 

##game_id restricts season ... check


def get_home_results(game_id):
    return X_merge.loc[(X_merge['game_id'] == game_id)&(X_merge['HoA'] == 'home'), :]


def get_away_results(game_id):
    return X_merge.loc[(X_merge['game_id'] == game_id)&(X_merge['HoA'] == 'away'), :]

#below row will come from df_result (game_id ) and from will be the either home info or away info from X_merge
 
def value(frame, key):
    if len(frame[key]) ==0:
       # print( "There is only one value for some feature in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    elif len(frame[key]) >=2:
        #print( "A feature value appears more than once in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    else: 
        return frame.iloc[0][key].astype(float)

def intValue(frame, key):
    if len(frame[key]) ==0:
        #print( "There emight be a missing (only 1 not 2?) value for some feature in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    elif len(frame[key]) >=2:
        #print( "A feature value appears more than once in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    else: 
        return int(frame.iloc[0][key])
    
def strValue(frame, key):
    if len(frame[key]) ==0:
        #print( "There might be a missing (only 1 not 2?) value for some feature in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    elif len(frame[key]) >=2:
        #print( "A feature value appears more than once in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    else: 
        return frame.iloc[0][key]
 
    
def add_results(row):
    home = get_home_results(row['game_id'])
    away = get_away_results(row['game_id'])
    
    id rows (to go with game_id)
    
    row['mp_date'] = intValue(home, 'mp_date')  #we can use the home one for these 2
    row['season'] = intValue(home, 'season')
    
    row['home_team'] = strValue(home, 'nhl_name')
    row['away_team'] = strValue(away, 'nhl_name')
    
    #odds (treat as a target ?)
    row['home_odds'] = value(home, 'Open')
    row['away_odds'] = value(away, 'Open')
    
    #target vars
    row['home_goals'] = value(home, 'goals')
    row['away_goals'] = value(away, 'goals')
    row['goal_difference']=value(home, 'goals')-value(away, 'goals')  #keep same name as before
    row['home_win'] = intValue(home, 'won')
    row['settled_in'] = strValue(home, 'settled_in')
    
    return row

In [52]:
X_merge.columns

Index(['Date', 'season_bet', 'VH', 'Team', 'Open', 'mp_date', 'HoA_bet',
       'nhl_name', 'game_id', 'team_id', 'HoA', 'won', 'settled_in',
       'head_coach', 'goals', 'shots', 'hits', 'pim', 'powerPlayOpportunities',
       'powerPlayGoals', 'faceOffWinPercentage', 'giveaways', 'takeaways',
       'blocked', 'startRinkSide', 'season_gm_stats', 'Vegas_pred_won'],
      dtype='object')

In [58]:

df_results = df_results.apply(add_results, axis=1).copy()


perc_null(df_results)

##
##df_results.dropna(inplace=True)

                 Total     Type   Percent
goal_difference    246  float64  0.017714
mp_date            123  float64  0.008857
season             123  float64  0.008857
home_team          123   object  0.008857
away_team          123   object  0.008857
home_odds          123  float64  0.008857
away_odds          123  float64  0.008857
home_goals         123  float64  0.008857
away_goals         123  float64  0.008857
home_win           123  float64  0.008857
settled_in         123   object  0.008857
game_id              0  float64  0.000000

In [37]:
##get_L_stats is called getStats in Leung's code

def get_L_stats(nhl_name, mp_date): #season is restriced because date is fixed as date -1 
    return L_data.loc[(L_data['nhl_name'] == nhl_name)& (L_data['mp_date'] == mp_date -1), :] #(!) -1 VERY important so you don't leak!

#the L_data stats are cumulative up to <= date ... so we grab cumulative stats up to mp_date = mp_date -1

##note the mp_date-1 !! this is what gives us the *previous day's'* cumulative stats for that te
##if the frame is empty value() will return NaN; this should happen for all first games for each team.    
    

##value is defined above when we created df_results from X_merge
    
def add_stats(row):
    home = get_L_stats(row['home_team'], row['mp_date'])
    away = get_L_stats(row['away_team'], row['mp_date'])

    row['CF%'] = value(home, 'cF%') - value(away, 'cF%')
    corsiShooting = (value(home, 'gF') / value(home, 'cF')) - (value(away, 'gF') / value(away, 'cF'))
    row['CSh%'] = corsiShooting * 100
    corsiSave = (1 - (value(home, 'gA') / value(home, 'cA'))) - (1 - (value(away, 'gA') / value(away, 'cA')))
    row['CSv%'] = corsiSave * 100
    row['FF%'] = value(home, 'fF%') - value(away, 'fF%')
    fenwickShooting = (value(home, 'gF') / value(home, 'fF')) - (value(away, 'gF') / value(away, 'fF'))
    row['FSh%'] = fenwickShooting * 100
    fenwickSave = (1 - (value(home, 'gA') / value(home, 'fA'))) - (1 - (value(away, 'gA') / value(away, 'fA')))
    row['FSv%'] = fenwickSave * 100
    row['GDiff'] = (value(home, 'gF60') - value(home, 'gA60')) - (value(away, 'gF60') - value(away, 'gA60'))
    row['GF%'] = value(home, 'gF%') - value(away, 'gF%')
    row['PDO'] = value(home, 'pDO') - value(away, 'pDO')
    row['PENDiff'] = (value(home, 'pEND') - value(home, 'pENT')) - (value(away, 'pEND') - value(away, 'pENT'))
    row['SF%'] = value(home, 'sF%') - value(away, 'sF%')
    row['SDiff'] = (value(home, 'sF60') - value(home, 'sA60')) - (value(away, 'sF60') - value(away, 'sA60'))
    shootingPercentage = (value(home, 'gF') / value(home, 'sF')) - (value(away, 'gF') / value(away, 'sF'))
    row['Sh%'] = shootingPercentage * 100
    row['Sv'] = value(home, 'sv%') - value(away, 'sv%')
    
    #L_data is missing GP, W, FOW% 
    #row['FOW%'] = value(home, 'FOW%') - value(away, 'FOW%')
    #winPercentage = (intValue(home, 'W') / intValue(home, 'GP')) - (intValue(away, 'W') / intValue(away, 'GP'))
    #row['W%'] = np.float64(winPercentage)
    return row

In [38]:
##test for code 
L_data.loc[(L_data['nhl_name'] == 'LAK')& (L_data['mp_date'] == 20151112 -1), :]['cF%']

48759    55.4
Name: cF%, dtype: float64

In [39]:
#test getStats:
get_L_stats('LAK', 20151112).iloc[0]['cF'].astype(float)

#test empty frame if no game ... 
len(get_L_stats('LAK', 20121112)['cF'])

0

In [40]:

df_results_L_data = df_results.apply(add_stats, axis =1).copy()   ##new df combines X_merge (results) and L_data

#check on diff between X_merge and L_data games:
#print(L_data.groupby(['mp_date, 'nhl_team']) ... hard to do grup by b/c team appears on all dates (whether played or not)

In [41]:
   
perc_null(df_results_L_data)

            Total     Type   Percent
CSh%         3501  float64  0.252124
CSv%         3501  float64  0.252124
Sh%          3501  float64  0.252124
SDiff        3501  float64  0.252124
SF%          3501  float64  0.252124
PENDiff      3501  float64  0.252124
PDO          3501  float64  0.252124
GF%          3501  float64  0.252124
GDiff        3501  float64  0.252124
FSv%         3501  float64  0.252124
FSh%         3501  float64  0.252124
FF%          3501  float64  0.252124
Sv           3501  float64  0.252124
CF%          3501  float64  0.252124
mp_date       123  float64  0.008858
settled_in    123   object  0.008858
home_win      123  float64  0.008858
away_goals    123  float64  0.008858
home_goals    123  float64  0.008858
away_odds     123  float64  0.008858
home_odds     123  float64  0.008858
away_team     123   object  0.008858
home_team     123   object  0.008858
season        123  float64  0.008858
game_id         0  float64  0.000000

In [46]:
# one of the games have 0 odds ... we will remove those
df_results_L_data= df_results_L_data.loc[ (df_results_L_data['home_odds'] != 0), :].copy()

In [62]:
df_results_L_data.shape

perc_null(df_results_L_data2)

            Total     Type  Percent
game_id         0  float64      0.0
CSv%            0  float64      0.0
Sh%             0  float64      0.0
SDiff           0  float64      0.0
SF%             0  float64      0.0
PENDiff         0  float64      0.0
PDO             0  float64      0.0
GF%             0  float64      0.0
GDiff           0  float64      0.0
FSv%            0  float64      0.0
FSh%            0  float64      0.0
FF%             0  float64      0.0
CSh%            0  float64      0.0
mp_date         0  float64      0.0
CF%             0  float64      0.0
settled_in      0   object      0.0
home_win        0  float64      0.0
away_goals      0  float64      0.0
home_goals      0  float64      0.0
away_odds       0  float64      0.0
home_odds       0  float64      0.0
away_team       0   object      0.0
home_team       0   object      0.0
season          0  float64      0.0
Sv              0  float64      0.0

In [61]:
df_results_L_data2 = df_results_L_data.dropna(inplace=False)  #drop na first 25%

In [66]:
df_results_L_data2

,game_id,mp_date,season,home_team,away_team,home_odds,away_odds,home_goals,away_goals,home_win,...,FSh%,FSv%,GDiff,GF%,PDO,PENDiff,SF%,SDiff,Sh%,Sv
2,2.008020e+09,20081005.0,20082009.0,NYR,TBL,-125.0,105.0,2.0,1.0,1.0,...,0.547778,0.547778,2.00,33.34,0.24,6.0,32.26,40.00,0.116144,0.12
3,2.008020e+09,20081005.0,20082009.0,PIT,OTT,-110.0,-110.0,1.0,3.0,0.0,...,2.919347,2.919347,1.86,14.28,9.52,2.0,-7.70,-9.30,4.761905,4.76
15,2.008020e+09,20081011.0,20082009.0,TOR,MTL,110.0,-130.0,1.0,6.0,0.0,...,6.916996,-1.953973,1.00,10.00,4.15,0.0,0.19,-2.00,6.773399,-2.63
16,2.008020e+09,20081011.0,20082009.0,OTT,DET,115.0,-135.0,2.0,3.0,0.0,...,2.736549,2.840909,1.48,14.55,6.42,-5.0,-5.65,-7.52,4.272014,2.14
17,2.008020e+09,20081011.0,20082009.0,NYI,STL,-125.0,105.0,5.0,2.0,1.0,...,-10.858586,0.366300,-4.00,-38.10,-16.69,-1.0,-2.73,-3.00,-18.881119,2.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12439,2.017021e+09,20180407.0,20172018.0,ARI,ANA,130.0,-150.0,0.0,3.0,0.0,...,-0.538754,-1.009587,-0.74,-6.80,-2.49,76.0,0.34,0.47,-0.790485,-1.70
12440,2.017021e+09,20180407.0,20172018.0,CGY,VGK,108.0,-128.0,7.0,1.0,1.0,...,-1.910827,-0.502267,-0.98,-8.62,-3.17,-22.0,0.29,0.42,-2.343425,-0.83
12441,2.017021e+09,20180407.0,20172018.0,EDM,VAN,-183.0,163.0,2.0,2.0,1.0,...,-0.451989,-0.233029,0.08,0.88,-0.72,0.0,2.91,3.64,-0.545256,-0.18
12442,2.017021e+09,20180407.0,20172018.0,LAK,DAL,-205.0,175.0,2.0,4.0,0.0,...,0.203981,1.032315,0.36,3.49,1.72,-1.0,-1.46,-1.76,0.439817,1.28
12443,2.017021e+09,20180407.0,20172018.0,SJS,MIN,-175.0,155.0,3.0,6.0,0.0,...,-0.866669,-0.089346,0.07,0.68,-0.84,58.0,2.87,3.57,-0.815267,-0.02

In [85]:
df_mp_teams.loc[(df_mp_teams['season'] == 20162017)&(df_mp_teams['nhl_name'] == 'LAK')&(df_mp_teams['mp_date'] <= 20141015), :   ]['team'].sum()

#df_LA = df_mp_teams.loc[(df_mp_teams['season'] == 20082009)&(df_mp_teams['nhl_name'] == 'LAK')&(df_mp_teams['mp_date'] <= 20090230), :   ]
#df_LA2 = df_game_team_stats.loc[(df_game_team_stats['season'] == 20082009)&(df_game_team_stats['nhl_name'] == 'LAK')&(df_game_team_stats['game_id'] <= 2008020919), :]

0

In [90]:
##from old notebook ... aha ... the counyt and sum are getting messed up by null values I think
    
    ##add stats part two ... using mp 
def get_mp_stats(season, nhl_name, mp_date):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date
    return df_mp_teams.loc[(df_mp_teams['season'] == season)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['mp_date'] <= mp_date-1), :   ]

#game_id is used as date:
def get_game_stats(season, nhl_name, game_id):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date
    return df_game_team_stats.loc[(df_game_team_stats['season'] == season)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['game_id'] <= game_id-1), :]
  
    
def do_sum(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    else: 
        return frame[key].sum()  ##! remove the .iloc[0] you want the whole frame now to count or sum


def do_count(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 3.14
    else: 
        return frame[key].count()
        
    
def add_missing_stats(row):
    mp_stats_home = get_mp_stats(row['season'], row['home_team'], row['mp_date'])
    mp_stats_away = get_mp_stats(row['season'], row['away_team'], row['mp_date'])
    game_stats_home = get_game_stats(row['season'], row['home_team'], row['game_id'])
    game_stats_away = get_game_stats(row['season'], row['away_team'], row['game_id'])
    
    GP_home = do_count(mp_stats_home, 'game_id')  #game_id is just to count
    GP_away = do_count(mp_stats_away, 'game_id')
    W_home = do_sum(game_stats_home, 'won') 
    W_away = do_sum(game_stats_away, 'won') 
    Wper_home = W_home/GP_home
    Wper_away = W_away/GP_away
    
    row['W%'] = Wper_home - Wper_away 
    
    FOL_home= do_sum(mp_stats_home,'faceOffsWonAgainst')
    FOL_away= do_sum(mp_stats_away,'faceOffsWonAgainst')
    FOW_home = do_sum(mp_stats_home,'faceOffsWonFor')
    FOW_away = do_sum(mp_stats_away,'faceOffsWonFor')
    FOper_home = FOW_home/(FOW_home+FOL_home)
    FOper_away = FOW_away/(FOW_away+FOL_away)
    
    row['FOW%'] = FOper_home-FOper_away

In [77]:
##a test for the code 

df_LA = df_mp_teams.loc[(df_mp_teams['season'] == 20082009)&(df_mp_teams['nhl_name'] == 'LAK')&(df_mp_teams['mp_date'] <= 20090230), :   ]
df_LA2 = df_game_team_stats.loc[(df_game_team_stats['season'] == 20082009)&(df_game_team_stats['nhl_name'] == 'LAK')&(df_game_team_stats['game_id'] <= 2008020919), :]

print(df_LA['game_id'].count())
print(df_LA2['game_id'].count())
#check game_id works as well as date:
list(df_LA2['game_id']) == list(df_LA['game_id']) #using game_id as date will work within a season

61
61

True

In [ ]:
#try dropping na first

df_results_L_data3 = df_results_L_data2.apply(add_missing_stats, axis =1).copy()

In [68]:
#perc_null(df_mp_teams)
df_results_L_data3

2        None
3        None
15       None
16       None
17       None
         ...
12439    None
12440    None
12441    None
12442    None
12443    None
Length: 10385, dtype: object

 ##add stats part two ... using mp to add FOW% and W% ... Leung's data is missing the entries 'GP' etc needed to do those
    
def get_mp_stats(season, nhl_name, mp_date):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date-1
    return df_mp_teams.loc[(df_mp_teams['season'] == season)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['mp_date'] <= mp_date-1), :   ]

##note the mp_date -1 (!)

#game_id is used as date (cell above checks this works)
def get_game_stats(season, nhl_name, game_id):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date-1
    return df_game_team_stats.loc[(df_game_team_stats['season'] == season)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['game_id'] <= game_id-1), :]
 
##note the game_id -1 (!)    
    
def do_sum(frame, key):
    if len(frame[key]) ==0:
        print( "There emight be a missing (only 1 not 2?) value for some feature in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    elif len(frame[key]) >=2:
        print( "A feature value appears more than once in X_merge for this game_id: ",  frame['game_id'] )
        return np.NaN
    else: 
        return frame[key].sum()  ##! remove the .iloc[0] you want the whole frame now to count or sum


def do_count(frame, key):
    if len(frame[key]) ==0:
        print( "Thermight be a missing (only 1 not 2?) value for some feature in df_game_stats for this game_id: ",  frame['game_id'] )
        return np.NaN
    elif len(frame[key]) >=2:
        print( "A feature value appears more than once in df_game_stats for this game_id: ",  frame['game_id'] )
        return np.NaN
    else: 
        return frame[key].count()
        
#will be applied to rows of df_results_L_data    
def add_missing_stats(row):
    mp_stats_home = get_mp_stats(row['season'], row['home_team'], row['mp_date'])
    mp_stats_away = get_mp_stats(row['season'], row['away_team'], row['mp_date'])
    game_stats_home = get_game_stats(row['season'], row['home_team'], row['game_id'])
    game_stats_away = get_game_stats(row['season'], row['away_team'], row['game_id'])
    
    GP_home = do_count(mp_stats_home, 'game_id')  #game_id is just to count
    GP_away = do_count(mp_stats_away, 'game_id')
    W_home = do_sum(game_stats_home, 'won') 
    W_away = do_sum(game_stats_away, 'won') 
    Wper_home = W_home/GP_home
    Wper_away = W_away/GP_home
    
    row['W%'] = Wper_home - Wper_away 
    
    FOL_home= do_sum(mp_stats_home,'faceOffsWonAgainst')
    FOL_away= do_sum(mp_stats_away,'faceOffsWonAgainst')
    FOW_home = do_sum(mp_stats_home,'faceOffsWonFor')
    FOW_away = do_sum(mp_stats_away,'faceOffsWonFor')
    FOper_home = FOW_home/(FOW_home+FOL_home)
    FOper_away = FOW_away/(FOW_away+FOL_away)
    
    
    row['FOW%'] = FOper_home-FOper_away

61
61

True

In [89]:
##should be about same NaN as df_result, around 29%?


df_results_L_data3 = df_results_L_data2.apply(add_missing_stats, axis =1).copy()

In [97]:
df_results_L_data3

2        None
3        None
15       None
16       None
17       None
         ...
12439    None
12440    None
12441    None
12442    None
12443    None
Length: 10385, dtype: object

In [ ]:
perc_null(df_results_L_data3)

In [122]:
df_results_L_data.columns

Index(['game_id', 'mp_date', 'season', 'home_team', 'away_team', 'home_odds',
       'away_odds', 'home_goals', 'away_goals', 'home_win', 'settled_in',
       'CF%', 'CSh%', 'CSv%', 'FF%', 'FSh%', 'FSv%', 'GDiff', 'GF%', 'PDO',
       'PENDiff', 'SF%', 'SDiff', 'Sh%', 'Sv', 'W%', 'FOW%', 'Vegas_pred'],
      dtype='object')

##from Git

##add stats part two ... using mp 
def get_mp_stats(season, nhl_name, mp_date):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date
    return df_mp_teams.loc[(df_mp_teams['season'] == season)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['mp_date'] <= mp_date), :   ]

#game_id is used as date:
def get_game_stats(season, nhl_name, game_id):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date
    return df_game_team_stats.loc[(df_game_team_stats['season'] == season)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['game_id'] <= game_id), :]
  
    
def do_sum(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 3.14
    else: 
        return frame[key].sum()  ##! remove the .iloc[0] you want the whole frame now to count or sum


def do_count(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 3.14
    else: 
        return frame[key].count()
        
    
def add_missing_stats(row):
    mp_stats_home = get_mp_stats(row['season'], row['home_team'], row['mp_date'])
    mp_stats_away = get_mp_stats(row['season'], row['away_team'], row['mp_date'])
    game_stats_home = get_game_stats(row['season'], row['home_team'], row['game_id'])
    game_stats_away = get_game_stats(row['season'], row['away_team'], row['game_id'])
    
    GP_home = do_count(mp_stats_home, 'game_id')  #game_id is just to count
    GP_away = do_count(mp_stats_away, 'game_id')
    W_home = do_sum(game_stats_home, 'won') 
    W_away = do_sum(game_stats_away, 'won') 
    Wper_home = W_home/GP_home
    Wper_away = W_away/GP_home
    
    row['W%'] = Wper_home - Wper_away 
    
    FOL_home= do_sum(mp_stats_home,'faceOffsWonAgainst')
    FOL_away= do_sum(mp_stats_away,'faceOffsWonAgainst')
    FOW_home = do_sum(mp_stats_home,'faceOffsWonFor')
    FOW_away = do_sum(mp_stats_away,'faceOffsWonFor')
    FOper_home = FOW_home/(FOW_home+FOL_home)
    FOper_away = FOW_away/(FOW_away+FOL_away)
    
    row['FOW%'] = FOper_home-FOper_away
    


df_results_L_data5 = df_results_L_data.head(60).apply(add_missing_stats, axis =1).copy()

In [106]:
df_results_L_data5

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
20    None
21    None
22    None
23    None
24    None
25    None
26    None
27    None
28    None
29    None
30    None
31    None
32    None
33    None
34    None
35    None
36    None
37    None
38    None
39    None
40    None
41    None
42    None
43    None
44    None
45    None
46    None
47    None
48    None
49    None
50    None
51    None
52    None
53    None
54    None
55    None
56    None
57    None
58    None
59    None
dtype: object

In [103]:
##constructing FavoriteW% .. measures how accurately the betting company predicted games in past for both home team and away team


#fav_stats = df_results_L_data.copy()  #we create an auxiliary stats repo ... so it doesn't get all tangled up

fav_stats = X_merge.copy()  #renamed fav_stats as convenience;  X_merge has a row for every team and pred_Vegas_won =0,1

def get_fav_stats(nhl_name, mp_date, season):
    return X_merge.loc[(fav_stats['nhl_name'] == season)&(fav_stats['nhl_name'] == nhl_name)& (fav_stats['mp_date'] <= mp_date -1), :] #(!) -1 VERY important so you don't leak!


    
##note the mp_date-1  we still need this because fav% is based on vegas pred plus actual results
##if the frame is empty value() will return NaN; this should happen for all first games for each team.    


    
def do_sum(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    else: 
        return frame[key].sum()  ##! remove the .iloc[0] you want the whole frame now to count or sum


def do_count(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 3.14
    else: 
        return frame[key].count()

def count_when_same(frame, key1, key2):      #homeFav
    if len(frame[key1])==0 or len(frame[key1])==0:
        #print( "There might be 0  values for some feature in X_merge for this game_id: ",  str(key1), str(key2), frame['game_id'] )
        return np.NaN
    elif len(frame[key1])!=len(frame[key1]): 
        #print( "There might be different values for some feature in X_merge for this game_id: ",  str(key1), str(key2), frame['game_id'] )
        return np.NaN
    else: 
        return (frame[key1] == frame[key2]).sum()
   
    #def count_when_diff(frame, key1, key2): #homeFav
#    return(frame[key1] != frame[key2]).sum()

#rows of df_results_L_data
def add_fav(row):
    home = get_fav_stats(row['home_team'], row['mp_date'], row['season'])  #stats on *all* previous (stricly previous) games of home team (H or A games)
    away = get_fav_stats(row['away_team'], row['mp_date'], row['season'])
   
    GP_home = do_count(home, 'game_id')  #game_id is just to count
    GP_away = do_count(away, 'game_id')
    home_win_pred_corr = count_when_same(home, 'Vegas_pred_won', 'won')
    away_win_pred_corr = count_when_same(away, 'Vegas_pred_won', 'won')
    home_fav =  home_win_pred_corr/GP_home   #this measures how accurate Vegas is with this home team in all games strictly passed (H or A)  
    away_fav =  away_win_pred_corr/GP_away #same for away team
    FavPerc = home_fav*away_fav 
     
    row['FavoritesW%'] =  FavPerc ## the product measures the overall accuracy of Vegas for both teams eg (0.9)(0.9) = 0.81, 0.9*0.5 = 0.45

In [71]:
##tests 
get_fav_stats('LAK', 20151112, 20152016 )

Empty DataFrame
Columns: [Date, season, VH, Team, Open, mp_date, HoA_bet, nhl_name, game_id, team_id, HoA, won, settled_in, head_coach, goals, shots, hits, pim, powerPlayOpportunities, powerPlayGoals, faceOffWinPercentage, giveaways, takeaways, blocked, startRinkSide, season_gm_stats, Vegas_pred_won]
Index: []

[0 rows x 27 columns]

In [104]:
 
df_results_L_data4 = df_results_L_data2.head(20).apply(add_fav, axis =1).copy()

df_results_L_data4 


#30% missing ... I'll take it!

2     None
3     None
15    None
16    None
17    None
19    None
21    None
22    None
23    None
25    None
29    None
30    None
31    None
32    None
33    None
34    None
35    None
36    None
37    None
38    None
dtype: object

In [96]:
df_results_L_data4

#df_results_L_data.shape

2        None
3        None
15       None
16       None
17       None
         ...
12439    None
12440    None
12441    None
12442    None
12443    None
Length: 10385, dtype: object

In [101]:

##!! I think I drop a lot here ... 30% ish (because Leung's data seems to be missing about 30% of games)
data_LJ = df_results_L_data.dropna(inplace=False).copy()
#df_results_L_data.shape

In [102]:

data_LJ.to_csv('/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Shaped_Data/data_LJ.csv')

In [35]:
##exrta investigation

df_temp = df_results.dropna(inplace = False).copy()

A = [set(df_betting['game_id']) , set(df_game_team_stats['game_id']) , set(df_results['game_id'])   ] 

for i in range(3):
    j = i + 1 %3   
    print(i, len(A[i])) 
    print(i, j, 'inters: ', len( set.intersection(A[i], A[j]) )
    print("all: ": len( set.intersection(A[0],A[1],A[2]))

In [35]:
common_game_ids = set.intersection( set(df_betting['game_id']) , set(df_game_team_stats['game_id']) , set(df_results['game_id'])   ) 
      
df_betting = df_betting.loc[df_betting['game_id'].isin(common_game_ids), :].copy()
df_game_team_stats = df_game_team_stats.loc[df_game_team_stats['game_id'].isin(common_game_ids), :].copy()
df_mp_teams = df_mp_teams.loc[df_mp_teams['game_id'].isin(common_game_ids), :].copy()