In [1]:

import pandas as pd
import numpy as np

In [2]:
## cleaning tool


def perc_null(X):
    
    total = X.isnull().sum().sort_values(ascending=False)
    data_types = X.dtypes
    percent = (X.isnull().sum()/X.isnull().count()).sort_values(ascending=False)

    missing_data = pd.concat([total, data_types, percent], axis=1, keys=['Total','Type' ,'Percent'])
    return missing_data

In [19]:
##? not sure what this is ... 
from numpy.core.numeric import True_

import pandas as pd
import numpy as np

##skip import lines because we are in notebook ... so those files with functions are copied above

## this function gives detailed info on NaN values of input df
#from data_clean import perc_null

#these functionas add a date column (x2) and correct mp season format

#from data_fix_dates import game_add_mp_date, bet_add_mp_date,  fix_mp_season 

#these functions assign nhl_names eg 'NYR' to bet, mp, and game; 
# functions use simple dictionaries

#from data_fix_team_names import bet_to_nhl, mp_to_nhl, game_to_nhl

##these are two different functions for assigning game_id to df_betting, based on team, date, H/A
##one uses df_game as look up table ... other uses df_mp_teams as look up table

#from data_bet_add_game_id import mp_to_bet_add_game_id, game_to_bet_add_game_id


##import all the files 

##file paths

Kaggle_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/"
mp_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/"
betting_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/"
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/nhl odds 2007-08.xlsx
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/


##Kaggle files

df_game = pd.read_csv(Kaggle_path+'game.csv')
df_game_team_stats = pd.read_csv(Kaggle_path+'game_teams_stats.csv')
df_game_skater_stats = pd.read_csv(Kaggle_path+'game_skater_stats.csv')
df_game_goalie_stats = pd.read_csv(Kaggle_path+'game_goalie_stats.csv')

##more subtle Kaggle features:
df_game_scratches = pd.read_csv(Kaggle_path+'game_scratches.csv')
df_game_officials = pd.read_csv(Kaggle_path+'game_officials.csv')
df_team_info = pd.read_csv(Kaggle_path+'team_info.csv')

## grab all the moneypuck data 

df_mp_teams = pd.read_csv(mp_path+'all_teams.csv')


## grab all betting data 
df1 = pd.read_excel(io = betting_path+'nhl odds 2007-08.xlsx')
df2 = pd.read_excel(io = betting_path+'nhl odds 2008-09.xlsx')
df3 = pd.read_excel(io = betting_path+'nhl odds 2009-10.xlsx')
df4 = pd.read_excel(io = betting_path+'nhl odds 2010-11.xlsx')
df5 = pd.read_excel(io = betting_path+'nhl odds 2011-12.xlsx')
df6 = pd.read_excel(io = betting_path+'nhl odds 2012-13.xlsx')
df7 = pd.read_excel(io = betting_path+'nhl odds 2013-14.xlsx')
df8 = pd.read_excel(io = betting_path+'nhl odds 2014-15.xlsx')
df9 = pd.read_excel(io = betting_path+'nhl odds 2015-16.xlsx')
df10 = pd.read_excel(io = betting_path+'nhl odds 2016-17.xlsx')
df11 = pd.read_excel(io = betting_path+'nhl odds 2017-18.xlsx')
df12 = pd.read_excel(io = betting_path+'nhl odds 2018-19.xlsx')
df13 = pd.read_excel(io = betting_path+'nhl odds 2019-20.xlsx')




df1['season'] = 20072008
df2['season'] = 20082009
df3['season'] = 20092010
df4['season'] = 20102011
df5['season'] = 20112012
df6['season'] = 20122013
df7['season'] = 20132014
df8['season'] = 20142015
df9['season'] = 20152016
df10['season'] = 20162017
df11['season'] = 20172018
df12['season'] = 20182019
df13['season'] = 20192020

##omit 20072008 
df_betting = pd.concat([df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13])

In [3]:
pathjj = '/Users/joejohns/' 
data_path = 'data_bootcamp/GitHub/final_project_nhl_prediction/Data/Leung_Data_Results/nhl_data_Leung.csv'
results_path = 'data_bootcamp/GitHub/final_project_nhl_prediction/Data/Leung_Data_Results/results_Leung.csv'
L_data = pd.read_csv(pathjj+data_path)
L_res = pd.read_csv(pathjj+results_path)
#df_data.dropna(inplace = True)

In [4]:

Kaggle_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/"
mp_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/"
betting_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/"
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/nhl odds 2007-08.xlsx
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/


##Kaggle files

df_game = pd.read_csv(Kaggle_path+'game.csv')
df_game_team_stats = pd.read_csv(Kaggle_path+'game_teams_stats.csv')

df_team_info = pd.read_csv(Kaggle_path+'team_info.csv')

In [224]:
np.sum(np.array([np.NaN]))

nan

In [5]:
df_game.sort_values(by = 'game_id').head()

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
18399,2000020001,20002001,R,2000-10-04T23:00:00Z,21,25,2,2,tbc win OT,right,Reunion Arena,/api/v1/venues/null,America/Chicago,-5,CDT
19132,2000020002,20002001,R,2000-10-05T23:00:00Z,9,6,4,4,tbc win OT,left,FleetCenter,/api/v1/venues/null,America/New_York,-4,EDT
18043,2000020003,20002001,R,2000-10-05T23:00:00Z,16,7,2,4,home win REG,left,HSBC Arena,/api/v1/venues/null,America/New_York,-4,EDT
18311,2000020004,20002001,R,2000-10-05T23:00:00Z,23,4,3,6,home win REG,right,First Union Center,/api/v1/venues/null,America/New_York,-4,EDT
18040,2000020005,20002001,R,2000-10-05T23:00:00Z,17,20,4,3,away win REG,right,Pengrowth Saddledome,/api/v1/venues/null,America/Denver,-6,MDT

In [6]:
L_res.head()

,Unnamed: 0,ID,Date,HomeTeam,AwayTeam,Result
0,0,https://www.nhl.com/gamecenter/2007020001,2007/09/29,Los Angeles Kings,Anaheim Ducks,H
1,1,https://www.nhl.com/gamecenter/2007020002,2007/09/30,Anaheim Ducks,Los Angeles Kings,H
2,2,https://www.nhl.com/gamecenter/2007020003,2007/10/03,Carolina Hurricanes,Montréal Canadiens,A
3,3,https://www.nhl.com/gamecenter/2007020004,2007/10/03,Detroit Red Wings,Anaheim Ducks,H
4,4,https://www.nhl.com/gamecenter/2007020005,2007/10/03,Toronto Maple Leafs,Ottawa Senators,A

In [7]:
L_data.head()

,cA,cA60,cF,cF%,cF60,cplusminus,dFSh%,dFSv%,dPDO,date,...,teamSlug,xFSh%,xFSv%,xGA,xGA60,xGF,xGF%,xGF60,xGplusminus,xPDO\
0,216,46.29,230,51.57,49.29,14,3.41,0.17,5.26,Oct 08 - Oct 16,...,washington-capitals,6.34,94.27,8.25,1.77,10.40,55.76,2.23,2.15,100.61\
1,166,55.33,148,47.13,49.33,-18,-0.90,-0.31,-2.65,Oct 08 - Oct 16,...,winnipeg-jets,6.94,93.17,8.61,2.87,8.05,48.32,2.68,-0.56,100.11\
2,94,40.29,125,57.08,53.57,31,0.53,-2.76,-2.21,Oct 08 - Oct 16,...,vancouver-canucks,7.32,94.31,4.04,1.73,7.46,64.86,3.20,3.42,101.62\
3,244,60.86,242,49.79,60.36,-2,-1.04,0.28,-0.53,Oct 08 - Oct 16,...,toronto-maple-leafs,8.86,92.24,14.52,3.62,15.86,52.21,3.96,1.34,101.1\
4,186,42.73,231,55.40,53.07,45,0.82,0.04,1.09,Oct 08 - Oct 16,...,tampa-bay-lightning,6.21,94.78,7.05,1.62,11.48,61.95,2.64,4.43,100.98\

In [8]:
L_data.columns

Index(['cA', 'cA60', 'cF', 'cF%', 'cF60', 'cplusminus', 'dFSh%', 'dFSv%',
       'dPDO', 'date', 'endDate', 'fA', 'fA60', 'fF', 'fF%', 'fF60', 'fSh%',
       'fSv%', 'fplusminus', 'gA', 'gA60', 'gF', 'gF%', 'gF60', 'gP',
       'gplusminus', 'pDO', 'pEND', 'pEND60', 'pENT', 'pENT60', 'pplusminus',
       'sA', 'sA60', 'sF', 'sF%', 'sF60', 'sh%', 'splusminus', 'sv%', 'tOI',
       'teamAbbreviation', 'teamId', 'teamLogoSvg', 'teamName', 'teamSlug',
       'xFSh%', 'xFSv%', 'xGA', 'xGA60', 'xGF', 'xGF%', 'xGF60', 'xGplusminus',
       'xPDO\'],
      dtype='object')

In [9]:
 L_data.loc[:,['date', 'endDate',   'teamAbbreviation', 'teamId']]  ##team id wrong! not franchise id either ...

                  date     endDate teamAbbreviation  teamId
0      Oct 08 - Oct 16  2014-10-16              WAS      30
1      Oct 08 - Oct 16  2014-10-16              WPG       2
2      Oct 08 - Oct 16  2014-10-16              VAN      29
3      Oct 08 - Oct 16  2014-10-16              TOR      28
4      Oct 08 - Oct 16  2014-10-16              TBL      27
...                ...         ...              ...     ...
55437  Oct 04 - Jan 07    2009-1-7              CAR       6
55438  Oct 04 - Jan 07    2009-1-7              BUF       4
55439  Oct 04 - Jan 07    2009-1-7              BOS       3
55440  Oct 04 - Jan 07    2009-1-7              ARI      23
55441  Oct 04 - Jan 07    2009-1-7              ANA       1

[55442 rows x 4 columns]

In [10]:
df_game.sort_values(by = 'game_id')

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
18399,2000020001,20002001,R,2000-10-04T23:00:00Z,21,25,2,2,tbc win OT,right,Reunion Arena,/api/v1/venues/null,America/Chicago,-5,CDT
19132,2000020002,20002001,R,2000-10-05T23:00:00Z,9,6,4,4,tbc win OT,left,FleetCenter,/api/v1/venues/null,America/New_York,-4,EDT
18043,2000020003,20002001,R,2000-10-05T23:00:00Z,16,7,2,4,home win REG,left,HSBC Arena,/api/v1/venues/null,America/New_York,-4,EDT
18311,2000020004,20002001,R,2000-10-05T23:00:00Z,23,4,3,6,home win REG,right,First Union Center,/api/v1/venues/null,America/New_York,-4,EDT
18040,2000020005,20002001,R,2000-10-05T23:00:00Z,17,20,4,3,away win REG,right,Pengrowth Saddledome,/api/v1/venues/null,America/Denver,-6,MDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22694,2019040651,20192020,A,2020-01-26T01:15:00Z,88,87,5,9,home win tbc,NaN,Enterprise Center,/api/v1/venues/5076,America/New_York,-5,EST
22695,2019040652,20192020,A,2020-01-26T02:15:00Z,90,89,10,5,away win tbc,NaN,Enterprise Center,/api/v1/venues/5076,America/New_York,-5,EST
22698,2019040652,20192020,A,2020-01-26T02:15:00Z,90,89,10,5,away win tbc,NaN,Enterprise Center,/api/v1/venues/5076,America/New_York,-5,EST
22696,2019040653,20192020,A,2020-01-26T03:15:00Z,87,90,4,5,home win tbc,NaN,Enterprise Center,/api/v1/venues/5076,America/New_York,-5,EST
22699,2019040653,20192020,A,2020-01-26T03:15:00Z,87,90,4,5,home win tbc,NaN,Enterprise Center,/api/v1/venues/5076,America/New_York,-5,EST

In [11]:
##Copied from v3_Mege

In [12]:
## cleaning tool


def perc_null(X):
    
    total = X.isnull().sum().sort_values(ascending=False)
    data_types = X.dtypes
    percent = (X.isnull().sum()/X.isnull().count()).sort_values(ascending=False)

    missing_data = pd.concat([total, data_types, percent], axis=1, keys=['Total','Type' ,'Percent'])
    return missing_data

In [13]:
##fixing dates and season label 

import pandas as pd
import numpy as np

def to_string(n):
    s = str(n)
    if len(s) ==1:
        return "0"+s
    else:
        return s

#makes mp_date for L_data '2014-1-16' --> 20140116 (integer)
    
def L_to_mp_date(s):
    ymd = s.split('-')
    y = ymd[0]
    m = ymd[1]
    d = ymd[2]
    if len(m) ==1:
        m = '0'+m
    if len(d) == 1:
        d = '0'+d
    return int(y+m+d)

#test '2014-1-16'.split('-')
#make_mp_date('2014-10-16')    
    
    
##for assigning dates in df_game
#takes in date_time date and returns integer yyyymmdd eg 20080904
##note this is df_mp format

def game_add_mp_date(date_time):
    d = date_time.day
    m = date_time.month
    y = date_time.year
    dd = to_string(d)
    mm = to_string(m)
    yyyy = str(y)
    return(int(yyyy+mm+dd))

##test 
date_time1 = pd.to_datetime('2016-10-19T00:30:00Z')
date_time2 = pd.to_datetime('2008-09-19T00:30:00Z')

print("two tests for game_add_mp_date:")
print(game_add_mp_date(date_time1) == 20161019)
print(game_add_mp_date(date_time2)==20080919)
print(" ")
##for assigning dates to df_betting
#takes in ingegers date = 913 or 1026 season = 20082009 
# returns  returns integer yyyymmdd eg 20080904
#note this is df_mp format

def bet_add_mp_date(date, season):
    d = str(date)
    s = str(season)
    if len(d) == 3:
        d = "0"+d 
    if (900 < date):
        y= s[:4]
    else:
        y = s[4:]
    return int(y+d)

##test
print("??three tests for bed_add_mp_date:")
print(bet_add_mp_date(912, 20082009) == 20080912)
print(bet_add_mp_date(1025,20102011) == 20101025)
print(bet_add_mp_date(227,20102011) == 20110227)
print(" ")

##fix season format for df_mp
##takes in integer 2008 and returns 20082009
##note: I have verified in df_mp for two seasons 2008 labels 20082009

def fix_mp_season(n):
    return int(str(n)+str(n+1))

def L_add_season(mp_date):
    st = str(mp_date)
    y = st[0:4]
    ym1 = str(int(y)-1) 
    yp1 =  str(int(y)+1)
    
    m = st[4:6]
    d = st[6:8]
    if 9 <= int(m) <= 12:
        return int(y+yp1)
    if 1 <= int(m) <= 8:
        return int(ym1+y)

##tests
print("two tests for fix_mp_season:")
print(fix_mp_season(2008) == 20082009)
print(fix_mp_season(2019) == 20192020)
print(" ")

print("three tests for L_add_season:")
print(L_add_season('20140119')==20132014)
print(L_add_season('20140912')==20142015)

    
print(" ")


print("three tests for L_to_mp_season:")
print(L_to_mp_date('2014-10-16')==20141016)
print(L_to_mp_date('2014-1-16')==20140116)
print(L_to_mp_date('2014-1-6')==20140106)
    
print(" ")

two tests for game_add_mp_date:
True
True

??three tests for bed_add_mp_date:
True
True
True

two tests for fix_mp_season:
True
True

three tests for L_add_season:
True
True

three tests for L_to_mp_season:
True
True
True

In [14]:
"yyyymmdd"[4:6]

'mm'

In [15]:
##fix team names
##Leung dropped all the ATL games so I should do same 

L_to_nhl_dic = {'ANA': 'ANA',
 'ARI': 'ARI',
 'ATL': 'ATL',
 'BOS': 'BOS',
 'BUF': 'BUF',
 'CAR': 'CAR',
 'CBJ': 'CBJ',
 'CAL': 'CGY',
 'CHI': 'CHI',
 'COL': 'COL',
 'DAL': 'DAL',
 'DET': 'DET',
 'EDM': 'EDM',
 'FLA': 'FLA',
 'LAK': 'LAK',
 'MIN': 'MIN',
 'MON': 'MTL',
 'NJD': 'NJD',
 'NSH': 'NSH',
 'NYI': 'NYI',
 'NYR': 'NYR',
 'OTT': 'OTT',
 'PHI': 'PHI',
 'PIT': 'PIT',
 'SJS': 'SJS',
 'STL': 'STL',
 'TBL': 'TBL',
 'TOR': 'TOR',
 'VAN': 'VAN',
 'VGK': 'VGK',
 'WPG': 'WPG',
 'WAS': 'WSH'}


mp_to_nhl_dic = {'ANA': 'ANA',
 'ARI': 'ARI',
 'ATL': 'ATL',
 'BOS': 'BOS',
 'BUF': 'BUF',
 'CAR': 'CAR',
 'CBJ': 'CBJ',
 'CGY': 'CGY',
 'CHI': 'CHI',
 'COL': 'COL',
 'DAL': 'DAL',
 'DET': 'DET',
 'EDM': 'EDM',
 'FLA': 'FLA',
 'L.A': 'LAK',
 'MIN': 'MIN',
 'MTL': 'MTL',
 'N.J': 'NJD',
 'NSH': 'NSH',
 'NYI': 'NYI',
 'NYR': 'NYR',
 'OTT': 'OTT',
 'PHI': 'PHI',
 'PIT': 'PIT',
 'S.J': 'SJS',
 'STL': 'STL',
 'T.B': 'TBL',
 'TOR': 'TOR',
 'VAN': 'VAN',
 'VGK': 'VGK',
 'WPG': 'WPG',
 'WSH': 'WSH'}

bet_to_nhl_dic = {'Anaheim': 'ANA',
 'Arizona': 'ARI',
 'Arizonas': 'ARI',
 'Atlanta': 'ATL',
 'Boston': 'BOS',
 'Buffalo': 'BUF',
 'Calgary': 'CGY',
 'Carolina': 'CAR',
 'Chicago': 'CHI',
 'Colorado': 'COL',
 'Columbus': 'CBJ',
 'Dallas': 'DAL',
 'Detroit': 'DET',
 'Edmonton': 'EDM',
 'Florida': 'FLA',
 'LosAngeles': 'LAK',
 'Minnesota': 'MIN',
 'Montreal': 'MTL',
 'NYIslanders': 'NYI',
 'NYRangers': 'NYR',
 'Nashville': 'NSH',
 'NewJersey': 'NJD',
 'Ottawa': 'OTT',
 'Philadelphia': 'PHI',
 'Phoenix': 'ARI',
 'Pittsburgh': 'PIT',
 'SanJose': 'SJS',
 'St.Louis': 'STL',
 'Tampa': 'TBL',
 'TampaBay': 'TBL',
 'Toronto': 'TOR',
 'Vancouver': 'VAN',
 'Vegas': 'VGK',
 'Washington': 'WSH',
 'Winnipeg': 'WPG',
 'WinnipegJets': 'WPG'}

game_to_nhl_dic = {1: 'NJD',
 4: 'PHI',
 26: 'LAK',
 14: 'TBL',
 6: 'BOS',
 3: 'NYR',
 5: 'PIT',
 17: 'DET',
 28: 'SJS',
 18: 'NSH',
 23: 'VAN',
 16: 'CHI',
 9: 'OTT',
 8: 'MTL',
 30: 'MIN',
 15: 'WSH',
 19: 'STL',
 24: 'ANA',
 27: 'ARI',
 2: 'NYI',
 10: 'TOR',
 13: 'FLA',
 7: 'BUF',
 20: 'CGY',
 21: 'COL',
 25: 'DAL',
 29: 'CBJ',
 52: 'WPG',
 22: 'EDM',
 54: 'VGK',
 12: 'CAR',
 53: 'ARI',
 11: 'ATL'}

def L_to_nhl(abbrevName):
    return L_to_nhl_dic[abbrevName]


def bet_to_nhl(Team):
    return bet_to_nhl_dic[Team]

def mp_to_nhl(team):
    return mp_to_nhl_dic[team]

def game_to_nhl(team_id):
    return game_to_nhl_dic[team_id]

##simple tests:
print(set(bet_to_nhl_dic.values()) == set(mp_to_nhl_dic.values()) )
print(set(bet_to_nhl_dic.values() )== set(game_to_nhl_dic.values()) )
print(set(mp_to_nhl_dic.values()) == set(game_to_nhl_dic.values()) )
print(set(mp_to_nhl_dic.values()) == set(L_to_nhl_dic.values()) )
print(set(game_to_nhl_dic.values()))
print(set(bet_to_nhl_dic.values()))
print(set(mp_to_nhl_dic.values()))
#print(set(mp_to_nhl_dic.values()) == set(L_data['teamAbbreviation']))
len(set(mp_to_nhl_dic.values()))

True
True
True
True
{'MTL', 'CGY', 'COL', 'PIT', 'OTT', 'ATL', 'ARI', 'CBJ', 'WSH', 'PHI', 'TBL', 'CAR', 'NYI', 'CHI', 'FLA', 'WPG', 'NYR', 'VAN', 'DAL', 'MIN', 'NSH', 'DET', 'TOR', 'STL', 'BOS', 'LAK', 'EDM', 'BUF', 'VGK', 'ANA', 'NJD', 'SJS'}
{'MTL', 'CGY', 'COL', 'ATL', 'OTT', 'PIT', 'ARI', 'CBJ', 'WSH', 'PHI', 'TBL', 'CAR', 'NYI', 'CHI', 'FLA', 'WPG', 'NYR', 'VAN', 'DAL', 'MIN', 'NSH', 'DET', 'TOR', 'STL', 'BOS', 'LAK', 'EDM', 'BUF', 'VGK', 'ANA', 'NJD', 'SJS'}
{'MTL', 'CGY', 'COL', 'ATL', 'OTT', 'PIT', 'ARI', 'CBJ', 'WSH', 'PHI', 'TBL', 'CAR', 'NYI', 'CHI', 'FLA', 'WPG', 'NYR', 'VAN', 'DAL', 'MIN', 'NSH', 'DET', 'TOR', 'STL', 'BOS', 'LAK', 'EDM', 'BUF', 'VGK', 'ANA', 'NJD', 'SJS'}

32

In [16]:
set(L_data['teamAbbreviation']).difference( set(mp_to_nhl_dic.values()))

{'CAL', 'MON', 'WAS'}

In [17]:
set(mp_to_nhl_dic.values()).difference(set(L_data['teamAbbreviation']))

{'ATL', 'CGY', 'MTL', 'WSH'}

In [18]:
##assign game_id to df_betting (two ways)

##these two functions 
# assign game_id to df_betting ... using two different look up tables, df_game and df_mp_teams
##note the following error codes are assigned if a game is not found or found more than once 
# if a home game is empty: 80    #8 is for h
# if a home game has >= 2 entries: 82
# if an away game is empty: 10   #1 is for a
# if an away game has >= 12 entries: 82

#df_betting['mp_game_id'] =  np.vectorize(mp_to_bet_add_game_id, excluded={0})(df_mp_teams, df_betting['mp_date'], df_betting['nhl_name'], df_betting['VH'] ) 


        
def game_to_bet_add_game_id(df_game_team_stats, mp_date, nhl_name, VH):##put VH in there! duh
    if VH == 'H':
        ## this h and (also a) is an array of values ... it  may be empty; we expect exactly one element; might have >=2 or 0  if something is wrong
        h = df_game.loc[(df_game_team_stats['mp_date'] == mp_date)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['HoA'] == 'home'),  :]['game_id'].values
        if len(h) ==1:
            return h[0]
        elif len(h)==0:  #and mp_date < 2010000:
            return 80
            print(mp_date)
        elif len(h) > 1:
            return 82
    if VH == 'V':
        a = df_game.loc[(df_game_team_stats['mp_date'] == mp_date)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['HoA'] == 'away'),  :]['game_id']
        if len(a) ==1:
            return a[0]
        elif len(a)==0:
            return 220
        elif len(a) > 1:
            return 222



def mp_to_bet_add_game_id(df_mp_teams, mp_date, nhl_name, VH):##put VH in there! duh
    if VH == 'H':
        h = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['home_or_away'] == 'HOME'),  :]['game_id'].values
        if len(h) ==1:
            return h[0]
        elif len(h)==0: 
            return 80   
            print(mp_date)
        elif len(h) > 1:
            return 82
    if VH == 'V':
        a = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['home_or_away'] == 'AWAY'),  :]['game_id'].values
        if len(a) ==1:
            return a[0]
        elif len(a)==0:
            return 10   
        elif len(a) > 1:
            return 12

    if VH == 'N':
        n = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name),  :]['game_id'].values
        if len(n) ==1:
            return n[0]
        elif len(n)==0:
            return 130   
        elif len(n) > 1:
            return 132
        
    else:
        return 26
    

def mp_to_bet_add_game_id_no_VH(df_mp_teams, mp_date, nhl_name):##put VH in there! duh
    ha = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name),  :]['game_id'].values
    if len(ha) ==1:
        return ha[0]
    elif len(ha)==0: 
        return 180   
    elif len(ha) > 1:
        return 182
    else:
        return 26

In [20]:
#df_team_info

In [21]:
#df_mp_teams

In [22]:

### set up list of all the df's for easy for loops
data_frames_all = [df_mp_teams, 
df_betting,
df_game,
df_game_team_stats, 
df_game_goalie_stats,
df_team_info,
df_game_officials,
df_game_scratches, 
df_game_skater_stats]

##for now just worry about joining these ones:

data_frames = [df_mp_teams, df_betting, df_game_team_stats]

In [23]:
df_game_team_stats.shape #before droping duplicates

(52610, 17)

In [24]:


df_betting = df_betting.loc[:, ['Date', 'season','VH', 'Team', 'Open']].copy()
df_mp_teams.rename(columns={"teamId": "team_id", 'gameDate': 'mp_date', 'gameId':'game_id' }, inplace = True)
##note there are other column names which differ, but team_id, mp_date, game_id are key for joining so we  
##make it consistent

df_mp_teams_big = df_mp_teams.copy()
##only has the rows for all situations (divide num rows by 5)
df_mp_teams = df_mp_teams.loc[(df_mp_teams['situation'] == 'all'), :] #&(df_mp_teams['playoffGame']==0), :].copy()

##restrict types to all situations later before merge 

df_game_team_stats.drop_duplicates(inplace = True)
df_game_team_stats = df_game_team_stats[~df_game_team_stats['team_id'].isin([87,88,89,90])].copy()
df_betting = df_betting[~(df_betting['VH'] == 'N')].copy()

In [25]:
df_game_team_stats.shape

(47460, 17)

In [26]:


df_mp_teams['season'] = np.vectorize(fix_mp_season)(df_mp_teams.loc[:,'season']).copy()


##restrict seasons; 
seasons = []
for n in range(2008,2020):
    seasons.append(int(str(n)+str(n+1)))

#check seasons look ok
print(seasons)

[20082009, 20092010, 20102011, 20112012, 20122013, 20132014, 20142015, 20152016, 20162017, 20172018, 20182019, 20192020]

/Users/joejohns/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [27]:
df_mp_teams['season'].value_counts()

20182019    2716
20172018    2710
20132014    2646
20152016    2642
20142015    2638
20092010    2636
20102011    2636
20162017    2634
20112012    2632
20082009    2628
20192020    2424
20202021    1736
20122013    1612
Name: season, dtype: int64

In [28]:
# fix these: 'endDate', 'teamAbbreviation'
L_data['mp_date'] = np.vectorize(L_to_mp_date)(L_data['endDate']).copy() 
L_data['nhl_name'] = np.vectorize(L_to_nhl)(L_data['teamAbbreviation']).copy()

In [29]:
L_data['season'] = np.vectorize(L_add_season)(L_data['mp_date'])
L_data.columns

Index(['cA', 'cA60', 'cF', 'cF%', 'cF60', 'cplusminus', 'dFSh%', 'dFSv%',
       'dPDO', 'date', 'endDate', 'fA', 'fA60', 'fF', 'fF%', 'fF60', 'fSh%',
       'fSv%', 'fplusminus', 'gA', 'gA60', 'gF', 'gF%', 'gF60', 'gP',
       'gplusminus', 'pDO', 'pEND', 'pEND60', 'pENT', 'pENT60', 'pplusminus',
       'sA', 'sA60', 'sF', 'sF%', 'sF60', 'sh%', 'splusminus', 'sv%', 'tOI',
       'teamAbbreviation', 'teamId', 'teamLogoSvg', 'teamName', 'teamSlug',
       'xFSh%', 'xFSv%', 'xGA', 'xGA60', 'xGF', 'xGF%', 'xGF60', 'xGplusminus',
       'xPDO\', 'mp_date', 'nhl_name', 'season'],
      dtype='object')

In [30]:
df_game_team_stats

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide
0,2016020045,4,away,False,REG,Dave Hakstol,4.0,27.0,30.0,6.0,4.0,2.0,50.9,12.0,9.0,11.0,left
1,2016020045,16,home,True,REG,Joel Quenneville,7.0,28.0,20.0,8.0,3.0,2.0,49.1,16.0,8.0,9.0,left
2,2017020812,24,away,True,OT,Randy Carlyle,4.0,34.0,16.0,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right
3,2017020812,7,home,False,OT,Phil Housley,3.0,33.0,17.0,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right
4,2015020314,21,away,True,REG,Patrick Roy,4.0,29.0,17.0,9.0,3.0,1.0,45.7,13.0,5.0,20.0,left
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52599,2018030415,6,home,False,REG,Bruce Cassidy,1.0,39.0,43.0,2.0,3.0,0.0,40.6,4.0,11.0,15.0,right
52602,2018030416,6,away,True,REG,Bruce Cassidy,5.0,32.0,27.0,10.0,4.0,1.0,41.3,4.0,10.0,16.0,right
52603,2018030416,19,home,False,REG,Craig Berube,1.0,29.0,29.0,20.0,4.0,0.0,58.7,12.0,11.0,9.0,right
52606,2018030417,19,away,True,REG,Craig Berube,4.0,20.0,36.0,2.0,0.0,0.0,49.0,7.0,8.0,21.0,right
52607,2018030417,6,home,False,REG,Bruce Cassidy,1.0,33.0,28.0,0.0,1.0,0.0,51.0,13.0,6.0,7.0,right

In [31]:
L_data = L_data.loc[L_data['season'].isin(seasons), :].copy()

df_betting = df_betting.loc[df_betting['season'].isin(seasons), :].copy()
#df_game_team_stats = df_game_team_stats.loc[df_game_team_stats['season'].isin(seasons), :].copy()
df_mp_teams = df_mp_teams.loc[df_mp_teams['season'].isin(seasons), :].copy()
#df_mp_teams = df_mp_teams.loc[df_mp_teams['season'].isin(seasons), :].copy()


## the index is no longer consecutive so we reset:

df_betting.reset_index(drop = True, inplace = True)
#df_game_team_stats.reset_index(drop = True, inplace = True)
df_mp_teams.reset_index(drop = True, inplace = True)


##! restrict df_game_team_stats later using the game_id

In [32]:
L_data.shape #drop by 10% right

(50040, 58)

In [33]:
df_betting.shape

(30300, 5)

In [34]:
df_betting['mp_date'] = np.vectorize(bet_add_mp_date)(df_betting['Date'], df_betting['season'])

HA_dic = { 'H': 'home', 'V': 'away', 'HOME': 'home', 'AWAY':'away'}
def add_HoA(h_or_a):  # h_or_a can be either of the formats used by mp or betting
    return HA_dic[h_or_a]

df_betting['HoA'] = df_betting['VH'].apply(add_HoA)

df_mp_teams['HoA'] = df_mp_teams['home_or_away'].apply(add_HoA)




df_betting['nhl_name'] = df_betting['Team'].apply(bet_to_nhl)
df_game_team_stats['nhl_name'] = df_game_team_stats['team_id'].apply(game_to_nhl)
df_mp_teams['nhl_name'] = df_mp_teams['name'].apply(mp_to_nhl)

df_betting['game_id'] =  np.vectorize(mp_to_bet_add_game_id_no_VH, excluded={0})(df_mp_teams, df_betting['mp_date'], df_betting['nhl_name'] )

In [146]:
L_data.columns

Index(['cA', 'cA60', 'cF', 'cF%', 'cF60', 'cplusminus', 'dFSh%', 'dFSv%',
       'dPDO', 'date', 'endDate', 'fA', 'fA60', 'fF', 'fF%', 'fF60', 'fSh%',
       'fSv%', 'fplusminus', 'gA', 'gA60', 'gF', 'gF%', 'gF60', 'gP',
       'gplusminus', 'pDO', 'pEND', 'pEND60', 'pENT', 'pENT60', 'pplusminus',
       'sA', 'sA60', 'sF', 'sF%', 'sF60', 'sh%', 'splusminus', 'sv%', 'tOI',
       'teamAbbreviation', 'teamId', 'teamLogoSvg', 'teamName', 'teamSlug',
       'xFSh%', 'xFSv%', 'xGA', 'xGA60', 'xGF', 'xGF%', 'xGF60', 'xGplusminus',
       'xPDO\', 'mp_date', 'nhl_name', 'season'],
      dtype='object')

In [35]:
list_df =[df_mp_teams, df_betting, df_game_team_stats]

common_game_ids = set.intersection( set(list_df[0]['game_id']) , set(list_df[1]['game_id']) , set(list_df[2]['game_id'])   ) 



df_betting = df_betting.loc[df_betting['game_id'].isin(common_game_ids), :].copy()
df_game_team_stats = df_game_team_stats.loc[df_game_team_stats['game_id'].isin(common_game_ids), :].copy()
df_mp_teams = df_mp_teams.loc[df_mp_teams['game_id'].isin(common_game_ids), :].copy()

In [152]:
L_data.columns

Index(['cA', 'cA60', 'cF', 'cF%', 'cF60', 'cplusminus', 'dFSh%', 'dFSv%',
       'dPDO', 'date', 'endDate', 'fA', 'fA60', 'fF', 'fF%', 'fF60', 'fSh%',
       'fSv%', 'fplusminus', 'gA', 'gA60', 'gF', 'gF%', 'gF60', 'gP',
       'gplusminus', 'pDO', 'pEND', 'pEND60', 'pENT', 'pENT60', 'pplusminus',
       'sA', 'sA60', 'sF', 'sF%', 'sF60', 'sh%', 'splusminus', 'sv%', 'tOI',
       'teamAbbreviation', 'teamId', 'teamLogoSvg', 'teamName', 'teamSlug',
       'xFSh%', 'xFSv%', 'xGA', 'xGA60', 'xGF', 'xGF%', 'xGF60', 'xGplusminus',
       'xPDO\', 'mp_date', 'nhl_name', 'season'],
      dtype='object')

In [36]:
##check consistency of nhl_names, HoA ...

df_mp_teams.sort_values(by = ['game_id', 'nhl_name'], inplace = True)
df_game_team_stats.sort_values(by = ['game_id', 'nhl_name'], inplace = True)
df_betting.sort_values(by = ['game_id', 'nhl_name'], inplace = True)

df_betting.reset_index(drop = True, inplace = True)
df_game_team_stats.reset_index(drop = True, inplace = True)
df_mp_teams.reset_index(drop = True, inplace = True)

In [155]:
X_merge['Vegawon']

0        1
1        0
2        0
3        1
4        1
        ..
29933    1
29934    1
29935    0
29936    1
29937    0
Name: won, Length: 29690, dtype: int64

In [ ]:
df_game.loc[df_game['game_id'] == 2012020159,:]

In [ ]:
df_game_team_stats.groupby('game_id')['goals'].sum().loc[(df_game_team_stats.groupby('game_id')['goals'].sum()==0)].index

In [ ]:
df_game.loc[df_game['game_id'].isin(bad_game_ids),:]

In [ ]:
df_game_team_stats.loc[df_game_team_stats.groupby('game_id')['goals'].sum()==0, 'game_id']

In [ ]:
df_game_team_stats.loc[df_game_team_stats['game_id'] == 2012020159, :]

In [38]:
X_merge = pd.merge(df_betting, df_game_team_stats, on = ['game_id', 'nhl_name'], how = 'inner', suffixes = ('_bet', '_gm_stats'))

#X_merge2 = pd.merge(X_merge, df_mp_teams, on = ['game_id', 'nhl_name', 'mp_date', 'season'], how = 'inner', suffixes = ('_merge', '_mp_teams'))

#print(2*len(common_game_ids),      X_merge2.shape[0])

In [162]:
X_merge.columns

Index(['Date', 'season', 'VH', 'Team', 'Open', 'mp_date', 'HoA_bet',
       'nhl_name', 'game_id', 'team_id', 'HoA', 'won', 'settled_in',
       'head_coach', 'goals', 'shots', 'hits', 'pim', 'powerPlayOpportunities',
       'powerPlayGoals', 'faceOffWinPercentage', 'giveaways', 'takeaways',
       'blocked', 'startRinkSide', 'Vegas_pred_won'],
      dtype='object')

In [39]:
X_merge = X_merge.loc[ (X_merge['nhl_name'] !='ATL'), :].copy()

X_merge.rename(columns = {'HoA_gm_stats':'HoA'}, inplace=True)
#X_merge_L3 = pd.merge(X_merge, L_data, on = ['nhl_name', 'mp_date', 'season'], how = 'left', suffixes = ('_merge', '_L'))

In [ ]:
X_merge.loc[ (X_merge['nhl_name'] !='ATL'), :].shape

In [ ]:
X_merge.shape

In [ ]:
X_merge_L2.shape

In [ ]:
perc_null(X_merge_L2).iloc[:, :]['Total']

In [ ]:
X_merge_L3.loc[X_merge_L3['fF%'].isnull(), 'season'].value_counts()

In [ ]:
X_merge2.shape

In [ ]:
L_data.columns

In [ ]:
set(X_merge['nhl_name']).symmetric_difference(set(L_data['nhl_name']))

In [ ]:
L_data['season'].value_counts()

In [ ]:
L_data.loc[:20, ['nhl_name', 'mp_date','season' ,'endDate']]

In [ ]:

#X_merge['HoA'] = df_mp_teams['HoA']

In [ ]:
X_merge.columns

In [ ]:
X_merge['settled_in']

In [41]:
#From X_merge use the game_id as a seed to make new df in the form of df_game ...(df_game is annoying bc of date)

list_game_ids = sorted(set(X_merge['game_id']))
len(sorted(set(X_merge['game_id'])))

df_results = pd.DataFrame({'game_id':list_game_ids})

In [ ]:
#df_betting

In [108]:
def Vegas_pred_home(Open):
    if Open < 0:
        return 1 
    elif Open > 0:
        return 0

In [118]:
df_results_L_data = df_results_L_data.loc[ (df_results_L_data['home_odds'] != 0), :].copy()

In [119]:
#df_results_L_data['Vegas_pred_home'] = np.vectorize(Vegas_pred)(df_results_L_data['home_odds']).copy()

In [ ]:
##X_merge_L3 is NOT what I want because I want to grab previous date ... also do the diff of H/A
#df_game.columns
#df_game['season'].value_counts()

#not needed:

def get_home_odds(nhl_name, mp_date): #could use game_id here ... stick with date to be consistent
    return df_betting.loc[(df_betting['nhl_name'] == nhl_name)& (L_data['mp_date'] == mp_date)&(df_betting['HoA'] == 'home'), :]

def get_away_odds(nhl_name, mp_date): #could use game_id here ... stick with date to be consistent
    return df_betting.loc[(df_betting['nhl_name'] == nhl_name)& (L_data['mp_date'] == mp_date)&(df_betting['HoA'] == 'home'), :]

In [42]:

###This is adapted from Leung's code.


def value(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 3.14
    else: 
        return frame.iloc[0][key].astype(float)

def intValue(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return 314
    else: 
        return int(frame.iloc[0][key])
    
def strValue(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    elif len(frame[key]) >=2:
        return "314"
    else: 
        return frame.iloc[0][key]
    
def get_home_results(game_id):
    return X_merge.loc[(X_merge['game_id'] == game_id)&(X_merge['HoA'] == 'home'), :]


def get_away_results(game_id):
    return X_merge.loc[(X_merge['game_id'] == game_id)&(X_merge['HoA'] == 'away'), :]

    
def add_results(row):
    home = get_home_results(row['game_id'])
    away = get_away_results(row['game_id'])
    
    row['mp_date'] = intValue(home, 'mp_date')
    row['season'] = intValue(home, 'season')
    
    row['home_team'] = strValue(home, 'nhl_name')
    row['away_team'] = strValue(away, 'nhl_name')
    
    
    row['home_odds'] = value(home, 'Open')
    row['away_odds'] = value(away, 'Open')
    
    row['home_goals'] = value(home, 'goals')
    row['away_goals'] = value(away, 'goals')
    
    row['home_win'] = intValue(home, 'won')
    row['settled_in'] = strValue(home, 'settled_in')
    
    return row

df_results = df_results.apply(add_results, axis=1).copy()

In [168]:
(df_results == 314).sum()

game_id       0
mp_date       0
season        0
home_team     0
away_team     0
home_odds     0
away_odds     0
home_goals    0
away_goals    0
home_win      0
settled_in    0
dtype: int64

In [169]:
df_results.shape

(14723, 11)

In [170]:
perc_null(df_results_L_data)

            Total     Type   Percent
FF%          4337  float64  0.294593
FSv%         4337  float64  0.294593
Sv           4337  float64  0.294593
Sh%          4337  float64  0.294593
SDiff        4337  float64  0.294593
SF%          4337  float64  0.294593
PENDiff      4337  float64  0.294593
PDO          4337  float64  0.294593
GF%          4337  float64  0.294593
CF%          4337  float64  0.294593
CSh%         4337  float64  0.294593
CSv%         4337  float64  0.294593
GDiff        4337  float64  0.294593
FSh%         4337  float64  0.294593
FOW%            0  float64  0.000000
W%              0  float64  0.000000
game_id         0  float64  0.000000
mp_date         0  float64  0.000000
settled_in      0   object  0.000000
home_win        0  float64  0.000000
away_goals      0  float64  0.000000
home_goals      0  float64  0.000000
away_odds       0  float64  0.000000
home_odds       0  float64  0.000000
away_team       0   object  0.000000
home_team       0   object  0.000000
season          0  float64  0.000000
Vegas_pred      0    int64  0.000000

In [ ]:
df_results.loc[df_results['mp_date'].isnull(),:]

In [ ]:
perc_null(df_results)

In [ ]:
df_results.shape

In [43]:
##!!!

df_results.dropna(inplace=True)

In [ ]:
df_results.shape  The ##250 ish rows ok ...

In [ ]:
L_data.shape

In [ ]:
sorted(L_data.columns)

In [ ]:
L_data.columns

In [ ]:
df_mp_teams.columns[70:]

In [ ]:
df_mp_teams.columns[30:70]

In [ ]:
df_mp_teams.columns[0:30]

In [ ]:
df_mp_teams

In [ ]:
L_data.columns

In [ ]:
df_.columns

In [ ]:
df_game_team_stats.columns

,cA,cA60,cF,cF%,cF60,cplusminus,dFSh%,dFSv%,dPDO,date,...,xGA,xGA60,xGF,xGF%,xGF60,xGplusminus,xPDO\,mp_date,nhl_name,season
0,216,46.29,230,51.57,49.29,14,3.41,0.17,5.26,Oct 08 - Oct 16,...,8.25,1.77,10.40,55.76,2.23,2.15,100.61\,20141016,WSH,20142015
1,166,55.33,148,47.13,49.33,-18,-0.90,-0.31,-2.65,Oct 08 - Oct 16,...,8.61,2.87,8.05,48.32,2.68,-0.56,100.11\,20141016,WPG,20142015
2,94,40.29,125,57.08,53.57,31,0.53,-2.76,-2.21,Oct 08 - Oct 16,...,4.04,1.73,7.46,64.86,3.20,3.42,101.62\,20141016,VAN,20142015
3,244,60.86,242,49.79,60.36,-2,-1.04,0.28,-0.53,Oct 08 - Oct 16,...,14.52,3.62,15.86,52.21,3.96,1.34,101.1\,20141016,TOR,20142015
4,186,42.73,231,55.40,53.07,45,0.82,0.04,1.09,Oct 08 - Oct 16,...,7.05,1.62,11.48,61.95,2.64,4.43,100.98\,20141016,TBL,20142015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55437,2349,54.98,2484,51.40,58.14,135,-0.86,0.12,-1.06,Oct 04 - Jan 07,...,117.11,2.74,123.05,51.24,2.88,5.94,99.87\,20090107,CAR,20082009
55438,2167,51.91,2123,49.49,50.86,-44,0.63,-0.67,-0.30,Oct 04 - Jan 07,...,100.01,2.40,103.80,50.93,2.49,3.79,100.38\,20090107,BUF,20082009
55439,2024,49.30,2094,50.85,51.00,70,2.10,1.20,4.70,Oct 04 - Jan 07,...,101.97,2.48,104.37,50.58,2.54,2.41,100.05\,20090107,BOS,20082009
55440,2456,58.78,2136,46.52,51.12,-320,0.23,-0.21,-0.18,Oct 04 - Jan 07,...,112.15,2.68,98.30,46.71,2.35,-13.85,100.19\,20090107,ARI,20082009
55441,2235,52.19,2072,48.11,48.38,-163,0.19,0.57,1.07,Oct 04 - Jan 07,...,121.53,2.84,109.76,47.46,2.56,-11.77,99.96\,20090107,ANA,20082009

In [124]:
L_data.head(2)

,cA,cA60,cF,cF%,cF60,cplusminus,dFSh%,dFSv%,dPDO,date,...,xGA,xGA60,xGF,xGF%,xGF60,xGplusminus,xPDO\,mp_date,nhl_name,season
0,216,46.29,230,51.57,49.29,14,3.41,0.17,5.26,Oct 08 - Oct 16,...,8.25,1.77,10.40,55.76,2.23,2.15,100.61\,20141016,WSH,20142015
1,166,55.33,148,47.13,49.33,-18,-0.90,-0.31,-2.65,Oct 08 - Oct 16,...,8.61,2.87,8.05,48.32,2.68,-0.56,100.11\,20141016,WPG,20142015

In [182]:
def getStats(nhl_name, mp_date):
    return L_data.loc[(L_data['nhl_name'] == nhl_name)& (L_data['mp_date'] == mp_date -1), :] #(!) -1 VERY important so you don't leak!

##note the mp_date-1 !! this is what gives us the *previous day's'* cumulative stats for that te
##if the frame is empty value() will return NaN; this should happen for all first games for each team.    
    ##last add ,,, fav%

    
    
def add_stats(row):
    home = getStats(row['home_team'], row['mp_date'])
    away = getStats(row['away_team'], row['mp_date'])

    row['CF%'] = value(home, 'cF%') - value(away, 'cF%')
    corsiShooting = (value(home, 'gF') / value(home, 'cF')) - (value(away, 'gF') / value(away, 'cF'))
    row['CSh%'] = corsiShooting * 100
    corsiSave = (1 - (value(home, 'gA') / value(home, 'cA'))) - (1 - (value(away, 'gA') / value(away, 'cA')))
    row['CSv%'] = corsiSave * 100
    row['FF%'] = value(home, 'fF%') - value(away, 'fF%')
    fenwickShooting = (value(home, 'gF') / value(home, 'fF')) - (value(away, 'gF') / value(away, 'fF'))
    row['FSh%'] = fenwickShooting * 100
    fenwickSave = (1 - (value(home, 'gA') / value(home, 'fA'))) - (1 - (value(away, 'gA') / value(away, 'fA')))
    row['FSv%'] = fenwickSave * 100
    row['GDiff'] = (value(home, 'gF60') - value(home, 'gA60')) - (value(away, 'gF60') - value(away, 'gA60'))
    row['GF%'] = value(home, 'gF%') - value(away, 'gF%')
    row['PDO'] = value(home, 'pDO') - value(away, 'pDO')
    row['PENDiff'] = (value(home, 'pEND') - value(home, 'pENT')) - (value(away, 'pEND') - value(away, 'pENT'))
    row['SF%'] = value(home, 'sF%') - value(away, 'sF%')
    row['SDiff'] = (value(home, 'sF60') - value(home, 'sA60')) - (value(away, 'sF60') - value(away, 'sA60'))
    shootingPercentage = (value(home, 'gF') / value(home, 'sF')) - (value(away, 'gF') / value(away, 'sF'))
    row['Sh%'] = shootingPercentage * 100
    row['Sv'] = value(home, 'sv%') - value(away, 'sv%')
    #row['FOW%'] = value(home, 'FOW%') - value(away, 'FOW%')
    #winPercentage = (intValue(home, 'W') / intValue(home, 'GP')) - (intValue(away, 'W') / intValue(away, 'GP'))
    #row['W%'] = np.float64(winPercentage)
    return row

df_results_L_data2 = df_results.head(60).apply(add_stats, axis =1)

In [183]:
df_results_L_data2

,game_id,mp_date,season,home_team,away_team,home_odds,away_odds,home_goals,away_goals,home_win,...,FSh%,FSv%,GDiff,GF%,PDO,PENDiff,SF%,SDiff,Sh%,Sv
0,2.008020e+09,20081004.0,20082009.0,TBL,NYR,-120.0,100.0,1.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.008020e+09,20081004.0,20082009.0,OTT,PIT,-115.0,-105.0,3.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.008020e+09,20081005.0,20082009.0,NYR,TBL,-125.0,105.0,2.0,1.0,1.0,...,0.547778,0.547778,2.00,33.34,0.24,6.0,32.26,40.00,0.116144,0.12
3,2.008020e+09,20081005.0,20082009.0,PIT,OTT,-110.0,-110.0,1.0,3.0,0.0,...,2.919347,2.919347,1.86,14.28,9.52,2.0,-7.70,-9.30,4.761905,4.76
4,2.008020e+09,20081009.0,20082009.0,DET,TOR,-300.0,240.0,2.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2.008020e+09,20081009.0,20082009.0,COL,BOS,-140.0,120.0,4.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2.008020e+09,20081009.0,20082009.0,VAN,CGY,-135.0,115.0,6.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2.008020e+09,20081009.0,20082009.0,SJS,ANA,-145.0,125.0,4.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2.008020e+09,20081010.0,20082009.0,NJD,NYI,-230.0,190.0,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2.008020e+09,20081010.0,20082009.0,NYR,CHI,-145.0,125.0,4.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2.008020e+09,20081010.0,20082009.0,CAR,FLA,-170.0,150.0,6.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2.008020e+09,20081010.0,20082009.0,BUF,MTL,-120.0,100.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2.008020e+09,20081010.0,20082009.0,STL,NSH,-120.0,100.0,5.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2.008020e+09,20081010.0,20082009.0,DAL,CBJ,-175.0,155.0,4.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2.008020e+09,20081011.0,20082009.0,TOR,MTL,110.0,-130.0,1.0,6.0,0.0,...,6.916996,-1.953973,1.00,10.00,4.15,0.0,0.19,-2.00,6.773399,-2.63
16,2.008020e+09,20081011.0,20082009.0,OTT,DET,115.0,-135.0,2.0,3.0,0.0,...,2.736549,2.840909,1.48,14.55,6.42,-5.0,-5.65,-7.52,4.272014,2.14
17,2.008020e+09,20081011.0,20082009.0,NYI,STL,-125.0,105.0,5.0,2.0,1.0,...,-10.858586,0.366300,-4.00,-38.10,-16.69,-1.0,-2.73,-3.00,-18.881119,2.19
18,2.008020e+09,20081011.0,20082009.0,PHI,NYR,-145.0,125.0,3.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2.008020e+09,20081011.0,20082009.0,WSH,CHI,-140.0,120.0,4.0,2.0,1.0,...,3.718821,-11.618590,-1.00,3.03,-5.74,-2.0,5.65,9.00,3.052326,-8.79
21,2.008020e+09,20081011.0,20082009.0,PIT,NJD,-135.0,115.0,1.0,2.0,0.0,...,1.488095,-3.787879,-1.48,-21.22,-4.53,5.0,-3.14,-3.48,1.300170,-5.83
22,2.008020e+09,20081011.0,20082009.0,TBL,CAR,-110.0,-110.0,3.0,4.0,0.0,...,-12.210012,4.353741,-3.00,-26.67,-12.88,0.0,-8.78,-11.00,-20.000000,7.12
23,2.008020e+09,20081011.0,20082009.0,NSH,DAL,-125.0,105.0,3.0,1.0,1.0,...,-3.760684,0.816993,-2.07,-15.87,-8.02,-8.0,-3.45,-3.71,-3.812317,-4.21
24,2.008020e+09,20081011.0,20082009.0,MIN,BOS,-145.0,125.0,4.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2.008020e+09,20081011.0,20082009.0,CGY,VAN,-145.0,125.0,4.0,5.0,0.0,...,-16.666667,-16.666667,-12.00,-100.00,-52.18,-6.0,4.16,4.00,-26.086957,-26.09
26,2.008020e+09,20081011.0,20082009.0,ARI,CBJ,-150.0,130.0,3.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2.008020e+09,20081011.0,20082009.0,SJS,LAK,-215.0,185.0,3.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2.008020e+09,20081012.0,20082009.0,EDM,COL,-130.0,110.0,3.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2.008020e+09,20081012.0,20082009.0,ANA,ARI,-190.0,170.0,2.0,4.0,0.0,...,-5.000000,-6.111111,-5.00,-55.00,-12.86,-7.0,-9.42,-13.00,-6.551724,-6.31
30,2.008020e+09,20081012.0,20082009.0,LAK,SJS,130.0,-150.0,0.0,1.0,0.0,...,-1.841869,-1.250845,-4.50,-52.78,-3.39,-9.0,-42.06,-48.00,-0.844278,-2.56
31,2.008020e+09,20081013.0,20082009.0,TOR,STL,-120.0,100.0,4.0,4.0,0.0,...,-4.388889,-0.045455,-2.00,-16.67,-5.94,-6.0,-2.95,-4.50,-7.175926,1.23
32,2.008020e+09,20081013.0,20082009.0,NYI,BUF,120.0,-140.0,1.0,7.0,0.0,...,5.189414,-2.954292,1.00,10.00,3.52,1.0,-4.08,-3.50,7.222222,-3.70
33,2.008020e+09,20081013.0,20082009.0,NYR,NJD,-125.0,105.0,4.0,1.0,1.0,...,2.709911,-1.364653,0.28,-3.51,1.57,3.0,-7.92,-8.85,3.695324,-2.12
34,2.008020e+09,20081013.0,20082009.0,PHI,MTL,-125.0,105.0,3.0,5.0,0.0,...,0.100578,-8.279125,-3.14,-34.92,-12.11,-3.0,0.50,0.57,-0.576037,-11.53
35,2.008020e+09,20081013.0,20082009.0,WSH,VAN,-135.0,115.0,5.0,1.0,1.0,...,-5.321900,-8.357245,-3.89,-26.27,-18.81,-5.0,8.34,11.05,-8.908635,-9.90
36,2.008020e+09,20081013.0,20082009.0,CAR,DET,120.0,-140.0,1.0,3.0,0.0,...,5.302121,0.286738,1.45,8.82,6.39,-1.0,-7.44,-9.65,7.875458,-1.49
37,2.008020e+09,20081013.0,20082009.0,CHI,NSH,-150.0,130.0,2.0,2.0,0.0,...,-0.875682,-0.815025,-1.50,-12.12,-0.12,0.0,-10.56,-11.00,-1.712089,1.59
38,2.008020e+09,20081014.0,20082009.0,PIT,PHI,-140.0,120.0,3.0,2.0,1.0,...,-1.451347,6.319184,0.87,2.86,7.36,1.0,-11.99,-14.12,-2.105263,9.46
40,2.008020e+09,20081014.0,20082009.0,CGY,COL,-135.0,115.0,5.0,4.0,1.0,...,-1.437741,0.111037,-2.39,-16.19,0.29,-5.0,-16.21,-17.95,-0.925926,1.21
41,2.008020e+09,20081014.0,20082009.0,LAK,ANA,115.0,-135.0,6.0,3.0,1.0,...,-1.995614,6.000000,1.00,-7.27,3.89,7.0,-13.44,-12.50,-1.746324,5.64
42,2.008020e+09,20081014.0,20082009.0,SJS,CBJ,-220.0,190.0,5.0,2.0,1.0,...,-2.189531,6.343125,2.48,33.85,5.51,14.0,13.73,15.07,-2.793494,8.31
43,2.008020e+09,20081015.0,20082009.0,NYR,BUF,-145.0,125.0,1.0,3.0,0.0,...,-1.512129,-1.786183,-0.97,-13.33,-3.72,-3.0,-1.97,-1.54,-1.267606,-2.45
44,2.008020e+09,20081015.0,20082009.0,MTL,BOS,-175.0,155.0,3.0,3.0,1.0,...,-1.176471,5.879156,2.10,20.59,6.38,2.0,2.18,2.80,-0.551942,6.93
45,2.008020e+09,20081015.0,20082009.0,CHI,ARI,-135.0,115.0,4.0,1.0,1.0,...,-5.076726,-4.906621,-3.20,-32.50,-11.70,-2.0,0.67,1.40,-5.270655,-6.42
46,2.008020e+09,20081015.0,20082009.0,DAL,NSH,-175.0,155.0,6.0,4.0,1.0,...,0.981695,-2.033406,-1.14,-8.21,-0.46,4.0,-8.37,-8.05,1.161946,-1.62
47,2.008020e+09,20081015.0,20082009.0,ANA,EDM,-160.0,140.0,2.0,3.0,0.0,...,-5.172414,-7.799145,-3.67,-30.00,-18.97,-12.0,14.02,14.66,-9.122807,-9.85
49,2.008020e+09,20081016.0,20082009.0,PIT,WSH,-135.0,115.0,3.0,4.0,0.0,...,-3.255906,4.913076,-1.23,-9.15,6.08,7.0,-21.92,-25.41,-2.953297,9.04
50,2.008020e+09,20081016.0,20082009.0,TBL,NYI,-150.0,130.0,3.0,4.0,0.0,...,-1.175214,4.288618,0.37,-0.43,4.79,-1.0,-12.90,-16.52,-1.086957,5.87
51,2.008020e+09,20081016.0,20082009.0,FLA,MIN,-110.0,-110.0,2.0,6.0,0.0,...,-4.111111,-4.863424,-1.98,-14.87,-11.76,3.0,10.59,12.77,-5.662393,-6.10
52,2.008020e+09,20081016.0,20082009.0,DET,VAN,-190.0,170.0,3.0,4.0,0.0,...,-5.675841,0.964165,-0.31,0.00,-8.38,1.0,16.12,18.85,-10.892904,2.52
53,2.008020e+09,20081016.0,20082009.0,STL,DAL,-110.0,-110.0,6.0,1.0,1.0,...,0.819001,3.136476,0.33,2.17,4.75,-3.0,-6.53,-6.62,0.940814,3.80
54,2.008020e+09,20081016.0,20082009.0,COL,PHI,-135.0,115.0,5.0,2.0,1.0,...,1.233588,-2.276532,0.30,3.48,-1.92,-1.0,5.38,6.40,1.012101,-2.94
55,2.008020e+09,20081017.0,20082009.0,OTT,ARI,-150.0,130.0,6.0,3.0,1.0,...,-0.854701,-0.712007,-0.34,-3.33,-0.40,-10.0,-2.03,-2.52,0.000000,-0.39
56,2.008020e+09,20081017.0,20082009.0,NYR,TOR,-215.0,185.0,0.0,0.0,1.0,...,0.940420,3.444414,2.21,20.71,5.68,7.0,6.26,6.90,0.842294,4.84
57,2.008020e+09,20081017.0,20082009.0,CBJ,NSH,-125.0,105.0,5.0,3.0,1.0,...,-0.251572,-0.937275,-0.61,-4.00,-1.22,-3.0,-0.42,-0.18,-2.011236,0.79
58,2.008020e+09,20081017.0,20082009.0,BUF,VAN,-155.0,135.0,5.0,2.0,1.0,...,-1.076298,4.049043,1.45,21.43,1.07,5.0,11.92,12.34,-4.444444,5.51
59,2.008020e+09,20081017.0,20082009.0,CGY,EDM,-140.0,120.0,3.0,4.0,0.0,...,-1.540179,-8.919767,-2.95,-22.50,-14.21,-3.0,9.99,11.48,-2.653598,-11.56
60,2.008020e+09,20081017.0,20082009.0,ANA,SJS,-110.0,-110.0,4.0,0.0,1.0,...,-2.333836,-7.634494,-4.50,-44.47,-14.41,-16.0,-4.89,-5.25,-3.917460,-10.49
61,2.008020e+09,20081017.0,20082009.0,LAK,CAR,100.0,-120.0,4.0,3.0,1.0,...,-0.762147,2.099318,-0.33,-2.38,3.12,5.0,-10.14,-9.67,1.056212,2.06
62,2.008020e+09,20081018.0,20082009.0,DAL,COL,-140.0,120.0,4.0,5.0,0.0,...,-1.308557,-0.188976,-1.47,-10.00,-1.62,-4.0,-7.57,-8.79,-0.101937,-1.52
63,2.008020e+09,20081018.0,20082009.0,MTL,ARI,-210.0,180.0,4.0,1.0,1.0,...,1.042144,3.386881,2.00,19.39,8.26,-5.0,-2.26,-2.39,3.729604,4.53

In [150]:
L_data

,cA,cA60,cF,cF%,cF60,cplusminus,dFSh%,dFSv%,dPDO,date,...,xGA,xGA60,xGF,xGF%,xGF60,xGplusminus,xPDO\,mp_date,nhl_name,season
0,216,46.29,230,51.57,49.29,14,3.41,0.17,5.26,Oct 08 - Oct 16,...,8.25,1.77,10.40,55.76,2.23,2.15,100.61\,20141016,WSH,20142015
1,166,55.33,148,47.13,49.33,-18,-0.90,-0.31,-2.65,Oct 08 - Oct 16,...,8.61,2.87,8.05,48.32,2.68,-0.56,100.11\,20141016,WPG,20142015
2,94,40.29,125,57.08,53.57,31,0.53,-2.76,-2.21,Oct 08 - Oct 16,...,4.04,1.73,7.46,64.86,3.20,3.42,101.62\,20141016,VAN,20142015
3,244,60.86,242,49.79,60.36,-2,-1.04,0.28,-0.53,Oct 08 - Oct 16,...,14.52,3.62,15.86,52.21,3.96,1.34,101.1\,20141016,TOR,20142015
4,186,42.73,231,55.40,53.07,45,0.82,0.04,1.09,Oct 08 - Oct 16,...,7.05,1.62,11.48,61.95,2.64,4.43,100.98\,20141016,TBL,20142015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55437,2349,54.98,2484,51.40,58.14,135,-0.86,0.12,-1.06,Oct 04 - Jan 07,...,117.11,2.74,123.05,51.24,2.88,5.94,99.87\,20090107,CAR,20082009
55438,2167,51.91,2123,49.49,50.86,-44,0.63,-0.67,-0.30,Oct 04 - Jan 07,...,100.01,2.40,103.80,50.93,2.49,3.79,100.38\,20090107,BUF,20082009
55439,2024,49.30,2094,50.85,51.00,70,2.10,1.20,4.70,Oct 04 - Jan 07,...,101.97,2.48,104.37,50.58,2.54,2.41,100.05\,20090107,BOS,20082009
55440,2456,58.78,2136,46.52,51.12,-320,0.23,-0.21,-0.18,Oct 04 - Jan 07,...,112.15,2.68,98.30,46.71,2.35,-13.85,100.19\,20090107,ARI,20082009
55441,2235,52.19,2072,48.11,48.38,-163,0.19,0.57,1.07,Oct 04 - Jan 07,...,121.53,2.84,109.76,47.46,2.56,-11.77,99.96\,20090107,ANA,20082009

In [ ]:
"abcde"[0:4]

In [47]:
def add_season_from_id(game_id):
    id = str(game_id)
    y = int(id[0:4])
    yn = y+1
    return int(str(y)+str(yn))
#test 
add_season_from_id(2019021081)

20192020

In [48]:
df_game_team_stats['season'] = np.vectorize(add_season_from_id)(df_game_team_stats['game_id']).copy()
df_game_team_stats['won'] = df_game_team_stats['won'].apply(int)

In [68]:
df_LA = df_mp_teams.loc[(df_mp_teams['season'] == 20082009)&(df_mp_teams['nhl_name'] == 'LAK')&(df_mp_teams['mp_date'] <= 20090230), :   ]
df_LA2 = df_game_team_stats.loc[(df_game_team_stats['season'] == 20082009)&(df_game_team_stats['nhl_name'] == 'LAK')&(df_game_team_stats['game_id'] <= 2008020919), :]

In [76]:
df_LA['game_id'].sum()

122489248737

In [73]:
(df_LA2['game_id'] != df_LA['game_id']).sum()  #using game_id as date will work within a season

0

In [187]:
 ##add stats part two ... using mp 
def get_mp_stats(season, nhl_name, mp_date):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date
    return df_mp_teams.loc[(df_mp_teams['season'] == season)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['mp_date'] <= mp_date), :   ]

#game_id is used as date:
def get_game_stats(season, nhl_name, game_id):  #note each game has two rows, with each team listed ONCE under nhl_name; date<= mp_date
    return df_game_team_stats.loc[(df_game_team_stats['season'] == season)&(df_game_team_stats['nhl_name'] == nhl_name)
                                  &(df_game_team_stats['game_id'] <= game_id), :]
  
    
def do_sum(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    else: 
        return frame[key].sum()  ##! remove the .iloc[0] you want the whole frame now to count or sum


def do_count(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    else: 
        return frame[key].count()
        
    
def add_missing_stats(row):
    mp_stats_home = get_mp_stats(row['season'], row['home_team'], row['mp_date'])
    mp_stats_away = get_mp_stats(row['season'], row['away_team'], row['mp_date'])
    game_stats_home = get_game_stats(row['season'], row['home_team'], row['game_id'])
    game_stats_away = get_game_stats(row['season'], row['away_team'], row['game_id'])
    
    GP_home = do_count(mp_stats_home, 'game_id')  #game_id is just to count
    GP_away = do_count(mp_stats_away, 'game_id')
    W_home = do_sum(game_stats_home, 'won') 
    W_away = do_sum(game_stats_away, 'won') 
    Wper_home = W_home/GP_home
    Wper_away = W_away/GP_away
    
    row['W%'] = Wper_home - Wper_away 
    
    FOL_home= do_sum(mp_stats_home,'faceOffsWonAgainst')
    FOL_away= do_sum(mp_stats_away,'faceOffsWonAgainst')
    FOW_home = do_sum(mp_stats_home,'faceOffsWonFor')
    FOW_away = do_sum(mp_stats_away,'faceOffsWonFor')
    FOper_home = FOW_home/(FOW_home+FOL_home)
    FOper_away = FOW_away/(FOW_away+FOL_away)
    
    row['FOW%'] = FOper_home-FOper_away
    


df_results_L_data3 = df_results_L_data.head(10).apply(add_missing_stats, axis =1).copy()

In [189]:
df_results_L_data.columns

Index(['game_id', 'mp_date', 'season', 'home_team', 'away_team', 'home_odds',
       'away_odds', 'home_goals', 'away_goals', 'home_win', 'settled_in',
       'CF%', 'CSh%', 'CSv%', 'FF%', 'FSh%', 'FSv%', 'GDiff', 'GF%', 'PDO',
       'PENDiff', 'SF%', 'SDiff', 'Sh%', 'Sv', 'W%', 'FOW%', 'Vegas_pred'],
      dtype='object')

In [157]:
X_merge.columns

Index(['Date', 'season', 'VH', 'Team', 'Open', 'mp_date', 'HoA_bet',
       'nhl_name', 'game_id', 'team_id', 'HoA', 'won', 'settled_in',
       'head_coach', 'goals', 'shots', 'hits', 'pim', 'powerPlayOpportunities',
       'powerPlayGoals', 'faceOffWinPercentage', 'giveaways', 'takeaways',
       'blocked', 'startRinkSide', 'Vegas_pred_won'],
      dtype='object')

In [210]:
np.NaN/np.NaN

nan

In [218]:
#perc_null(fav_stats)

home = fav_stats.loc[(fav_stats['nhl_name'] == 'LAK')& (fav_stats['mp_date'] <= 20161022 -1)&(fav_stats['season'] == 20162017), :] #(!) -1 VERY important so you don't leak!
away = fav_stats.loc[(fav_stats['nhl_name'] == 'BOS')& (fav_stats['mp_date'] <= 20161022 -1)&(fav_stats['season'] == 20162017), :] #(!) -1 VERY important so you don't leak!
home['game_id'].sum()
GP_home = do_count(home, 'game_id')  #game_id is just to count
GP_away = do_count(away, 'game_id')
home_win_pred_corr = count_when_same(home, 'Vegas_pred_won', 'won')
away_win_pred_corr = count_when_same(away, 'Vegas_pred_won', 'won')
home_fav =  home_win_pred_corr/GP_home   #this measures how accurate Vegas is with this home team in all games strictly passed (H or A)  
away_fav =  away_win_pred_corr/GP_away #same for away team
print(GP_home)
print(away_fav) 
print(home_fav*away_fav)

4
0.75
0.375

In [219]:

#fav_stats = df_results_L_data.copy()  #we create an auxiliary stats repo ... so it doesn't get all tangled up

fav_stats = X_merge.copy()  #renamed fav_stats as convenience;  X_merge has a row for every team and pred_Vegas_won =0,1
def get_stats(nhl_name, mp_date, season):
    return fav_stats.loc[(fav_stats['nhl_name'] == nhl_name)& (fav_stats['mp_date'] <= mp_date -1)&(fav_stats['season'] == season), :] #(!) -1 VERY important so you don't leak!


    
##note the mp_date-1  we still need this because fav% is based on vegas pred plus actual results
##if the frame is empty value() will return NaN; this should happen for all first games for each team.    


    
def do_sum(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    else: 
        return frame[key].sum()  ##! remove the .iloc[0] you want the whole frame now to count or sum


def do_count(frame, key):
    if len(frame[key]) ==0:
        return np.NaN
    else: 
        return frame[key].count()

def count_when_same(frame, key1, key2):      #homeFav
    if len(frame[key1])==0 or len(frame[key1])==0:
        return np.NaN
    elif  len(frame[key1])!=len(frame[key1]): 
        return np.NaN
    else: 
        return (frame[key1] == frame[key2]).sum()
   
    #def count_when_diff(frame, key1, key2): #homeFav
#    return(frame[key1] != frame[key2]).sum()

def add_fav(row):
    home = get_stats(row['home_team'], row['mp_date'], row['season'])  #stats on all previous (stricly previous) games of home team (H or A games)
    away = get_stats(row['away_team'], row['mp_date'], row['season'])
   
    GP_home = do_count(home, 'game_id')  #game_id is just to count
    GP_away = do_count(away, 'game_id')
    home_win_pred_corr = count_when_same(home, 'Vegas_pred_won', 'won')
    away_win_pred_corr = count_when_same(home, 'Vegas_pred_won', 'won')
    if GP_home == 0 or GP_away ==0:
        return np.NaN
    else:
        home_fav =  home_win_pred_corr/GP_home   #this measures how accurate Vegas is with this home team in all games strictly passed (H or A)  
        away_fav =  away_win_pred_corr/GP_away #same for away team
        row['FavoritesW%'] = home_fav*away_fav ## the product measures the overall accuracy of Vegas for both teams eg (0.9)(0.9) = 0.81, 0.9*0.5 = 0.45
    

    
df_results_L_data2 = df_results.head(60).apply(add_fav, axis =1).copy()

In [220]:
df_results_L_data2

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
21    None
22    None
23    None
24    None
25    None
26    None
27    None
28    None
29    None
30    None
31    None
32    None
33    None
34    None
35    None
36    None
37    None
38    None
40    None
41    None
42    None
43    None
44    None
45    None
46    None
47    None
49    None
50    None
51    None
52    None
53    None
54    None
55    None
56    None
57    None
58    None
59    None
60    None
61    None
62    None
63    None
dtype: object

In [142]:
X_merge.loc[:, ['won', 'Vegas_pred_won','Open']].head(20)

    won  Vegas_pred_won  Open
0     1               0   100
1     0               1  -120
2     0               1  -115
3     1               1  -105
4     1               1  -125
5     0               0   105
6     1               1  -110
7     0               1  -110
8     0               1  -300
9     1               0   240
10    1               0   120
11    0               1  -140
12    0               0   115
13    1               1  -135
14    0               0   125
15    1               1  -145
16    1               1  -230
17    0               0   190
18    0               0   125
19    1               1  -145

In [161]:
X_merge['Vegas_pred_won'] = np.vectorize(Vegas_pred)(X_merge['Open'])

In [135]:
X_merge = X_merge.loc[~(X_merge['Open'] == 0), :].copy()

In [139]:
X_merge['won'] = X_merge['won'].apply(int).copy()

In [ ]:
np.vectorize(Vegas_pred)

In [131]:
X_merge['won'] = X_merge['won'].apply(int)
X_merge['Veg_pred_won']

0         True
1        False
2        False
3         True
4         True
         ...
29933     True
29934     True
29935    False
29936     True
29937    False
Name: won, Length: 29692, dtype: bool

In [ ]:
#test 
getStats('LAK', 20151112).iloc[0]['cF'].astype(float)

In [ ]:
#test empty frame if no game ... 
len(getStats('LAK', 20121112)['cF'])

In [104]:
perc_null(df_results_L_data) 

#30% missing ... I'll take it!


df_results_L_data.iloc[:20, 10:]

In [173]:
perc_null(df_results_L_data)

            Total     Type   Percent
FF%          4337  float64  0.294593
FSv%         4337  float64  0.294593
Sv           4337  float64  0.294593
Sh%          4337  float64  0.294593
SDiff        4337  float64  0.294593
SF%          4337  float64  0.294593
PENDiff      4337  float64  0.294593
PDO          4337  float64  0.294593
GF%          4337  float64  0.294593
CF%          4337  float64  0.294593
CSh%         4337  float64  0.294593
CSv%         4337  float64  0.294593
GDiff        4337  float64  0.294593
FSh%         4337  float64  0.294593
FOW%            0  float64  0.000000
W%              0  float64  0.000000
game_id         0  float64  0.000000
mp_date         0  float64  0.000000
settled_in      0   object  0.000000
home_win        0  float64  0.000000
away_goals      0  float64  0.000000
home_goals      0  float64  0.000000
away_odds       0  float64  0.000000
home_odds       0  float64  0.000000
away_team       0   object  0.000000
home_team       0   object  0.000000
season          0  float64  0.000000
Vegas_pred      0    int64  0.000000

In [144]:
#sorted(df_mp_teams.columns)