In [2]:
##from the vscode file... data_fix_season_cut_down ... 

import pandas as pd
import numpy as np


##import all the files 

##file paths

Kaggle_path = "/Users/joejohns/data_bootcamp/Final_Project_NHL_prediction/Data/Kaggle_Data_Ellis/"
mp_path = "/Users/joejohns/data_bootcamp/Final_Project_NHL_prediction/Data/Money_Puck_Data/"
betting_path = "/Users/joejohns/data_bootcamp/Final_Project_NHL_pJrediction/Data/Betting_Data/"

##Kaggle files

df_game = pd.read_csv(Kaggle_path+'game.csv')
df_game_team_stats = pd.read_csv(Kaggle_path+'game_teams_stats.csv')
df_game_skater_stats = pd.read_csv(Kaggle_path+'game_skater_stats.csv')
df_game_goalie_stats = pd.read_csv(Kaggle_path+'game_goalie_stats.csv')

##more subtle Kaggle features:
df_game_scratches = pd.read_csv(Kaggle_path+'game_scratches.csv')
df_game_officials = pd.read_csv(Kaggle_path+'game_officials.csv')
df_team_info = pd.read_csv(Kaggle_path+'team_info.csv')
#df_fran_info = pd.read_csv(Kaggle_path+'franchise_info.csv')

## grab all the moneypuck data 

df_mp_teams = pd.read_csv(mp_path+'all_teams.csv')


## grab all betting data 
df1 = pd.read_excel(io = betting_path+'nhl odds 2007-08.xlsx')
df2 = pd.read_excel(io = betting_path+'nhl odds 2008-09.xlsx')
df3 = pd.read_excel(io = betting_path+'nhl odds 2009-10.xlsx')
df4 = pd.read_excel(io = betting_path+'nhl odds 2010-11.xlsx')
df5 = pd.read_excel(io = betting_path+'nhl odds 2011-12.xlsx')
df6 = pd.read_excel(io = betting_path+'nhl odds 2012-13.xlsx')
df7 = pd.read_excel(io = betting_path+'nhl odds 2013-14.xlsx')
df8 = pd.read_excel(io = betting_path+'nhl odds 2014-15.xlsx')
df9 = pd.read_excel(io = betting_path+'nhl odds 2015-16.xlsx')
df10 = pd.read_excel(io = betting_path+'nhl odds 2016-17.xlsx')
df11 = pd.read_excel(io = betting_path+'nhl odds 2017-18.xlsx')
df12 = pd.read_excel(io = betting_path+'nhl odds 2018-19.xlsx')
df13 = pd.read_excel(io = betting_path+'nhl odds 2019-20.xlsx')




df1['season'] = 20072008
df2['season'] = 20082009
df3['season'] = 20092010
df4['season'] = 20102011
df5['season'] = 20112012
df6['season'] = 20122013
df7['season'] = 20132014
df8['season'] = 20142015
df9['season'] = 20152016
df10['season'] = 20162017
df11['season'] = 20172018
df12['season'] = 20182019
df13['season'] = 20192020

df_betting = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13])

##### restrict data sets 
## restrict data sets 
df_betting = df_betting.loc[:, ['Date', 'season','VH', 'Team', 'Open']].copy()
df_mp_teams.rename(columns={"teamId": "team_id"}, inplace = True)

df_mp_teams_all = df_mp_teams.loc[df_mp_teams['situation'] == 'all', :].copy()

##### restrict data sets 


df_betting = df_betting.loc[:, ['Date', 'season','VH', 'Team', 'Open']].copy()
df_mp_teams_all = df_mp_teams.loc[df_mp_teams['situation'] == 'all', :].copy()

##drop duplicates and one column had some NaN;
##note there are more nan values in df_game_skaters/team/goalies but I think df_mp gets those.

df_game.drop_duplicates(inplace = True)
df_game.drop(columns = ['home_rink_side_start'], inplace = True)

## fix seasons in df_mp (other 2 already have 20082009 format)


def fix_mp_season(n):
    return int(str(n)+str(n+1))

#test 
#fix_mp_season(2010)
df_mp_teams['season'] = df_mp_teams['season'].map(fix_mp_season)
df_mp_teams_all['season'] = df_mp_teams_all['season'].map(fix_mp_season)


##restrict seasons; 20082009 to 20192020 is the range common to all 3 df's
seasons = []
for n in range(2008,2020):
    seasons.append(int(str(n)+str(n+1)))

#check seasons look ok
print(seasons)

#restrict seasons:

##note: In notebook I checked that value counts of the seasons did not change after this
#restriction


df_betting = df_betting.loc[df_game['season'].isin(seasons), :].copy()
df_game = df_game.loc[df_game['season'].isin(seasons), :].copy()
df_mp_teams = df_mp_teams.loc[df_mp_teams['season'].isin(seasons), :].copy()
df_mp_teams_all = df_mp_teams_all.loc[df_mp_teams_all['season'].isin(seasons), :].copy()

##here is a count of how many games in each df ... approx the same ... so looks likely there 
##should be close to full overlap in game_id's


## the index is no longer consecutive so we reset:

df_betting.reset_index(drop = True, inplace = True)
df_game.reset_index(drop = True, inplace = True)
df_mp_teams.reset_index(drop = True, inplace = True)
df_mp_teams_all.reset_index(drop = True, inplace = True)

for seas in seasons:
    print(seas, len(df_mp_teams_all.loc[df_mp_teams['season']==seas])/2, len(df_game.loc[df_game['season']==seas]), len(df_betting.loc[df_betting['season']==seas])/2)

[20082009, 20092010, 20102011, 20112012, 20122013, 20132014, 20142015, 20152016, 20162017, 20172018, 20182019, 20192020]
20082009 1322.5 1230 1317.0
20092010 1317.5 1230 1318.0
20102011 1287.5 1319 1319.0
20112012 1402.0 1316 1315.0
20122013 787.5 806 806.0
20132014 1357.5 1323 1323.0
20142015 1300.0 1319 1319.0
20152016 1350.0 1321 1321.0
20162017 1355.0 1323 1317.0
20172018 1317.5 1363 1355.0
20182019 1287.5 1360 1358.0
20192020 1192.5 1215 1212.0

In [1]:
## check that df_mp and df_game have similar games ...

In [6]:
mp_to_nhl_dic = {'ANA': 'ANA',
 'ARI': 'ARI',
 'ATL': 'ATL',
 'BOS': 'BOS',
 'BUF': 'BUF',
 'CAR': 'CAR',
 'CBJ': 'CBJ',
 'CGY': 'CGY',
 'CHI': 'CHI',
 'COL': 'COL',
 'DAL': 'DAL',
 'DET': 'DET',
 'EDM': 'EDM',
 'FLA': 'FLA',
 'L.A': 'LAK',
 'MIN': 'MIN',
 'MTL': 'MTL',
 'N.J': 'NJD',
 'NSH': 'NSH',
 'NYI': 'NYI',
 'NYR': 'NYR',
 'OTT': 'OTT',
 'PHI': 'PHI',
 'PIT': 'PIT',
 'S.J': 'SJS',
 'STL': 'STL',
 'T.B': 'TBL',
 'TOR': 'TOR',
 'VAN': 'VAN',
 'VGK': 'VGK',
 'WPG': 'WPG',
 'WSH': 'WSH'}

In [7]:
nhl_names2 = ['ANA',
 'ARI',
 'ARI',
 'ATL',
 'BOS',
 'BUF',
 'CAR',
 'CBJ',
 'CGY',
 'CHI',
 'COL',
 'DAL',
 'DET',
 'EDM',
 'FLA',
 'LAK',
 'MIN',
 'MTL',
 'NJD',
 'NSH',
 'NYI',
 'NYR',
 'OTT',
 'PHI',
 'PHX',
 'PIT',
 'SJS',
 'STL',
 'TBL',
 'TBL',             
 'TOR',
 'VAN',
 'VGK',
 'WPG',
 'WPG',
 'WSH']

In [8]:
bet_to_nhl_dic = {'Anaheim': 'ANA',
 'Arizona': 'ARI',
 'Arizonas': 'ARI',
 'Atlanta': 'ATL',
 'Boston': 'BOS',
 'Buffalo': 'BUF',
 'Calgary': 'CGY',
 'Carolina': 'CAR',
 'Chicago': 'CHI',
 'Colorado': 'COL',
 'Columbus': 'CBJ',
 'Dallas': 'DAL',
 'Detroit': 'DET',
 'Edmonton': 'EDM',
 'Florida': 'FLA',
 'LosAngeles': 'LAK',
 'Minnesota': 'MIN',
 'Montreal': 'MTL',
 'NYIslanders': 'NYI',
 'NYRangers': 'NYR',
 'Nashville': 'NSH',
 'NewJersey': 'NJD',
 'Ottawa': 'OTT',
 'Philadelphia': 'PHI',
 'Phoenix': 'PHX',
 'Pittsburgh': 'PIT',
 'SanJose': 'SJS',
 'St.Louis': 'STL',
 'Tampa': 'TBL',
 'TampaBay': 'TBL',
 'Toronto': 'TOR',
 'Vancouver': 'VAN',
 'Vegas': 'VGK',
 'Washington': 'WSH',
 'Winnipeg': 'WPG',
 'WinnipegJets': 'WPG'}

In [9]:
def bet_to_nhl(Team):
    return bet_to_nhl_dic[Team]

def mp_to_nhl(team):
    return mp_to_nhl_dic[team]

def game_to_nhl(team_id):
    return df_team_info.loc[df_team_info['team_id'] == team_id, 'abbreviation'].values[0]

In [10]:
##need to drop team_id 87,88,89,90 from df_game

df_game = df_game[~df_game['away_team_id'].isin([87,88,89,90])].copy()
df_game = df_game[~df_game['home_team_id'].isin([87,88,89,90])].copy()
df_betting = df_betting[~(df_betting['VH'] == 'N')].copy()

In [11]:
df_betting['nhl_name'] = df_betting['Team'].apply(bet_to_nhl)

In [12]:
df_game['away_team'] = df_game['away_team_id'].apply(game_to_nhl)

In [13]:
df_game['home_team'] = df_game['home_team_id'].apply(game_to_nhl)

In [14]:
df_mp_teams['nhl_name'] = df_mp_teams['name'].apply(mp_to_nhl)

In [15]:
df_mp_teams_all['nhl_name'] = df_mp_teams_all['name'].apply(mp_to_nhl)

In [17]:
df_game.columns

Index(['game_id', 'season', 'type', 'date_time_GMT', 'away_team_id',
       'home_team_id', 'away_goals', 'home_goals', 'outcome', 'venue',
       'venue_link', 'venue_time_zone_id', 'venue_time_zone_offset',
       'venue_time_zone_tz', 'away_team', 'home_team'],
      dtype='object')

In [20]:
df_game.loc[9000:9006, ['away_team_id', 'away_team', 'home_team_id', 'home_team'   ]]

      away_team_id away_team  home_team_id home_team
9000            27       PHX            22       EDM
9001            52       WPG            12       CAR
9002            24       ANA            22       EDM
9003            17       DET            20       CGY
9004            19       STL            27       PHX
9005            17       DET            26       LAK
9006            22       EDM            25       DAL

In [22]:
df_team_info

,team_id,franchiseId,shortName,teamName,abbreviation,link
0,1,23,New Jersey,Devils,NJD,/api/v1/teams/1
1,4,16,Philadelphia,Flyers,PHI,/api/v1/teams/4
2,26,14,Los Angeles,Kings,LAK,/api/v1/teams/26
3,14,31,Tampa Bay,Lightning,TBL,/api/v1/teams/14
4,6,6,Boston,Bruins,BOS,/api/v1/teams/6
5,3,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
6,5,17,Pittsburgh,Penguins,PIT,/api/v1/teams/5
7,17,12,Detroit,Red Wings,DET,/api/v1/teams/17
8,28,29,San Jose,Sharks,SJS,/api/v1/teams/28
9,18,34,Nashville,Predators,NSH,/api/v1/teams/18
10,23,20,Vancouver,Canucks,VAN,/api/v1/teams/23
11,16,11,Chicago,Blackhawks,CHI,/api/v1/teams/16
12,9,30,Ottawa,Senators,OTT,/api/v1/teams/9
13,8,1,Montreal,Canadiens,MTL,/api/v1/teams/8
14,30,37,Minnesota,Wild,MIN,/api/v1/teams/30
15,15,24,Washington,Capitals,WSH,/api/v1/teams/15
16,19,18,St Louis,Blues,STL,/api/v1/teams/19
17,24,32,Anaheim,Ducks,ANA,/api/v1/teams/24
18,27,28,Phoenix,Coyotes,PHX,/api/v1/teams/27
19,2,22,NY Islanders,Islanders,NYI,/api/v1/teams/2
20,10,5,Toronto,Maple Leafs,TOR,/api/v1/teams/10
21,13,33,Florida,Panthers,FLA,/api/v1/teams/13
22,7,19,Buffalo,Sabres,BUF,/api/v1/teams/7
23,20,21,Calgary,Flames,CGY,/api/v1/teams/20
24,21,27,Colorado,Avalanche,COL,/api/v1/teams/21
25,25,15,Dallas,Stars,DAL,/api/v1/teams/25
26,29,36,Columbus,Blue Jackets,CBJ,/api/v1/teams/29
27,52,35,Winnipeg,Jets,WPG,/api/v1/teams/52
28,22,25,Edmonton,Oilers,EDM,/api/v1/teams/22
29,54,38,Vegas,Golden Knights,VGK,/api/v1/teams/54
30,12,26,Carolina,Hurricanes,CAR,/api/v1/teams/12
31,53,28,Arizona,Coyotes,ARI,/api/v1/teams/53
32,11,35,Atlanta,Thrashers,ATL,/api/v1/teams/11

In [33]:
df_game['date_time_GMT'] = pd.to_datetime(df_game['date_time_GMT'])

In [34]:
from datetime import datetime, timedelta

def  game_fix_date(date_time, offset):
    return date_time + timedelta( days = 0, hours = int(offset), minutes = 0)

df_game['date_time_local'] = np.vectorize(game_fix_date)(df_game['date_time_GMT'], df_game['venue_time_zone_offset'])

In [25]:
df_game[

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz,away_team,home_team
0,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,United Center,/api/v1/venues/null,America/Chicago,-5,CDT,PHI,CHI
1,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,KeyBank Center,/api/v1/venues/null,America/New_York,-4,EDT,ANA,BUF
2,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,MTS Centre,/api/v1/venues/null,America/Winnipeg,-5,CDT,COL,WPG
3,2015020849,20152016,R,2016-02-17T00:00:00Z,52,12,1,2,home win REG,PNC Arena,/api/v1/venues/null,America/New_York,-4,EDT,WPG,CAR
4,2017020586,20172018,R,2017-12-30T03:00:00Z,20,24,1,2,home win REG,Honda Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT,CGY,ANA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15120,2018030413,20182019,P,2019-06-02T00:00:00Z,6,19,7,2,away win REG,Enterprise Center,/api/v1/venues/5076,America/Chicago,-5,CDT,BOS,STL
15121,2018030414,20182019,P,2019-06-04T00:00:00Z,6,19,2,4,home win REG,Enterprise Center,/api/v1/venues/5076,America/Chicago,-6,CST,BOS,STL
15122,2018030415,20182019,P,2019-06-07T00:00:00Z,19,6,2,1,away win REG,TD Garden,/api/v1/venues/5085,America/New_York,-5,EST,STL,BOS
15123,2018030416,20182019,P,2019-06-10T00:00:00Z,6,19,5,1,away win REG,Enterprise Center,/api/v1/venues/5076,America/Chicago,-6,CST,BOS,STL
15124,2018030417,20182019,P,2019-06-13T00:00:00Z,19,6,4,1,away win REG,TD Garden,/api/v1/venues/5085,America/New_York,-5,EST,STL,BOS