In [1]:
## cleaning tool


def perc_null(X):
    
    total = X.isnull().sum().sort_values(ascending=False)
    data_types = X.dtypes
    percent = (X.isnull().sum()/X.isnull().count()).sort_values(ascending=False)

    missing_data = pd.concat([total, data_types, percent], axis=1, keys=['Total','Type' ,'Percent'])
    return missing_data

In [2]:
##fixing dates and season label 

import pandas as pd
import numpy as np

def to_string(n):
    s = str(n)
    if len(s) ==1:
        return "0"+s
    else:
        return s

##for assigning dates in df_game
#takes in date_time date and returns integer yyyymmdd eg 20080904
##note this is df_mp format

def game_add_mp_date(date_time):
    d = date_time.day
    m = date_time.month
    y = date_time.year
    dd = to_string(d)
    mm = to_string(m)
    yyyy = str(y)
    return(int(yyyy+mm+dd))

##test 
date_time1 = pd.to_datetime('2016-10-19T00:30:00Z')
date_time2 = pd.to_datetime('2008-09-19T00:30:00Z')

print("two tests for game_add_mp_date:")
print(game_add_mp_date(date_time1) == 20161019)
print(game_add_mp_date(date_time2)==20080919)
print(" ")
##for assigning dates to df_betting
#takes in ingegers date = 913 or 1026 season = 20082009 
# returns  returns integer yyyymmdd eg 20080904
#note this is df_mp format

def bet_add_mp_date(date, season):
    d = str(date)
    s = str(season)
    if len(d) == 3:
        d = "0"+d 
    if (900 < date):
        y= s[:4]
    else:
        y = s[4:]
    return int(y+d)

##test
print("??three tests for bed_add_mp_date:")
print(bet_add_mp_date(912, 20082009) == 20080912)
print(bet_add_mp_date(1025,20102011) == 20101025)
print(bet_add_mp_date(227,20102011) == 20110227)
print(" ")

##fix season format for df_mp
##takes in integer 2008 and returns 20082009
##note: I have verified in df_mp for two seasons 2008 labels 20082009

def fix_mp_season(n):
    return int(str(n)+str(n+1))

##tests
print("two tests for fix_mp_season:")
print(fix_mp_season(2008) == 20082009)
print(fix_mp_season(2019) == 20192020)
print(" ")

two tests for game_add_mp_date:
True
True

??three tests for bed_add_mp_date:
True
True
True

two tests for fix_mp_season:
True
True

In [3]:
##fix team names


mp_to_nhl_dic = {'ANA': 'ANA',
 'ARI': 'ARI',
 'ATL': 'ATL',
 'BOS': 'BOS',
 'BUF': 'BUF',
 'CAR': 'CAR',
 'CBJ': 'CBJ',
 'CGY': 'CGY',
 'CHI': 'CHI',
 'COL': 'COL',
 'DAL': 'DAL',
 'DET': 'DET',
 'EDM': 'EDM',
 'FLA': 'FLA',
 'L.A': 'LAK',
 'MIN': 'MIN',
 'MTL': 'MTL',
 'N.J': 'NJD',
 'NSH': 'NSH',
 'NYI': 'NYI',
 'NYR': 'NYR',
 'OTT': 'OTT',
 'PHI': 'PHI',
 'PIT': 'PIT',
 'S.J': 'SJS',
 'STL': 'STL',
 'T.B': 'TBL',
 'TOR': 'TOR',
 'VAN': 'VAN',
 'VGK': 'VGK',
 'WPG': 'WPG',
 'WSH': 'WSH'}

bet_to_nhl_dic = {'Anaheim': 'ANA',
 'Arizona': 'ARI',
 'Arizonas': 'ARI',
 'Atlanta': 'ATL',
 'Boston': 'BOS',
 'Buffalo': 'BUF',
 'Calgary': 'CGY',
 'Carolina': 'CAR',
 'Chicago': 'CHI',
 'Colorado': 'COL',
 'Columbus': 'CBJ',
 'Dallas': 'DAL',
 'Detroit': 'DET',
 'Edmonton': 'EDM',
 'Florida': 'FLA',
 'LosAngeles': 'LAK',
 'Minnesota': 'MIN',
 'Montreal': 'MTL',
 'NYIslanders': 'NYI',
 'NYRangers': 'NYR',
 'Nashville': 'NSH',
 'NewJersey': 'NJD',
 'Ottawa': 'OTT',
 'Philadelphia': 'PHI',
 'Phoenix': 'ARI',
 'Pittsburgh': 'PIT',
 'SanJose': 'SJS',
 'St.Louis': 'STL',
 'Tampa': 'TBL',
 'TampaBay': 'TBL',
 'Toronto': 'TOR',
 'Vancouver': 'VAN',
 'Vegas': 'VGK',
 'Washington': 'WSH',
 'Winnipeg': 'WPG',
 'WinnipegJets': 'WPG'}

game_to_nhl_dic = {1: 'NJD',
 4: 'PHI',
 26: 'LAK',
 14: 'TBL',
 6: 'BOS',
 3: 'NYR',
 5: 'PIT',
 17: 'DET',
 28: 'SJS',
 18: 'NSH',
 23: 'VAN',
 16: 'CHI',
 9: 'OTT',
 8: 'MTL',
 30: 'MIN',
 15: 'WSH',
 19: 'STL',
 24: 'ANA',
 27: 'ARI',
 2: 'NYI',
 10: 'TOR',
 13: 'FLA',
 7: 'BUF',
 20: 'CGY',
 21: 'COL',
 25: 'DAL',
 29: 'CBJ',
 52: 'WPG',
 22: 'EDM',
 54: 'VGK',
 12: 'CAR',
 53: 'ARI',
 11: 'ATL'}

def bet_to_nhl(Team):
    return bet_to_nhl_dic[Team]

def mp_to_nhl(team):
    return mp_to_nhl_dic[team]

def game_to_nhl(team_id):
    return game_to_nhl_dic[team_id]

##simple tests:
print(set(bet_to_nhl_dic.values()) == set(mp_to_nhl_dic.values()) )
print(set(bet_to_nhl_dic.values() )== set(game_to_nhl_dic.values()) )
print(set(mp_to_nhl_dic.values()) == set(game_to_nhl_dic.values()) )

print(set(game_to_nhl_dic.values()))
print(set(bet_to_nhl_dic.values()))
print(set(mp_to_nhl_dic.values()))

True
True
True
{'PIT', 'CHI', 'FLA', 'EDM', 'SJS', 'MTL', 'STL', 'NJD', 'CBJ', 'NYI', 'ARI', 'DET', 'CGY', 'NYR', 'BOS', 'MIN', 'PHI', 'VAN', 'DAL', 'COL', 'TBL', 'LAK', 'NSH', 'OTT', 'TOR', 'BUF', 'VGK', 'ATL', 'WSH', 'ANA', 'WPG', 'CAR'}
{'PIT', 'CHI', 'FLA', 'EDM', 'SJS', 'MTL', 'STL', 'NJD', 'CBJ', 'NYI', 'ARI', 'DET', 'CGY', 'NYR', 'BOS', 'MIN', 'PHI', 'VAN', 'DAL', 'COL', 'LAK', 'NSH', 'OTT', 'TBL', 'BUF', 'TOR', 'VGK', 'ATL', 'ANA', 'WSH', 'WPG', 'CAR'}
{'PIT', 'CHI', 'FLA', 'EDM', 'SJS', 'MTL', 'STL', 'NJD', 'CBJ', 'NYI', 'ARI', 'DET', 'CGY', 'NYR', 'BOS', 'MIN', 'PHI', 'VAN', 'DAL', 'COL', 'LAK', 'NSH', 'OTT', 'TBL', 'BUF', 'TOR', 'VGK', 'ATL', 'ANA', 'WPG', 'WSH', 'CAR'}

In [4]:
##assign game_id to df_betting (two ways)

##these two functions 
# assign game_id to df_betting ... using two different look up tables, df_game and df_mp_teams
##note the following error codes are assigned if a game is not found or found more than once 
# if a home game is empty: 80    #8 is for h
# if a home game has >= 2 entries: 82
# if an away game is empty: 10   #1 is for a
# if an away game has >= 12 entries: 82

#df_betting['mp_game_id'] =  np.vectorize(mp_to_bet_add_game_id, excluded={0})(df_mp_teams, df_betting['mp_date'], df_betting['nhl_name'], df_betting['VH'] ) 


        
def game_to_bet_add_game_id(df_game_team_stats, mp_date, nhl_name, VH):##put VH in there! duh
    if VH == 'H':
        ## this h and (also a) is an array of values ... it  may be empty; we expect exactly one element; might have >=2 or 0  if something is wrong
        h = df_game.loc[(df_game_team_stats['mp_date'] == mp_date)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['HoA'] == 'home'),  :]['game_id'].values
        if len(h) ==1:
            return h[0]
        elif len(h)==0:  #and mp_date < 2010000:
            return 80
            print(mp_date)
        elif len(h) > 1:
            return 82
    if VH == 'V':
        a = df_game.loc[(df_game_team_stats['mp_date'] == mp_date)&(df_game_team_stats['nhl_name'] == nhl_name)&(df_game_team_stats['HoA'] == 'away'),  :]['game_id']
        if len(a) ==1:
            return a[0]
        elif len(a)==0:
            return 220
        elif len(a) > 1:
            return 222



def mp_to_bet_add_game_id(df_mp_teams, mp_date, nhl_name, VH):##put VH in there! duh
    if VH == 'H':
        h = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['home_or_away'] == 'HOME'),  :]['game_id'].values
        if len(h) ==1:
            return h[0]
        elif len(h)==0: 
            return 80   
            print(mp_date)
        elif len(h) > 1:
            return 82
    if VH == 'V':
        a = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name)&(df_mp_teams['home_or_away'] == 'AWAY'),  :]['game_id'].values
        if len(a) ==1:
            return a[0]
        elif len(a)==0:
            return 10   
        elif len(a) > 1:
            return 12

    if VH == 'N':
        n = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name),  :]['game_id'].values
        if len(n) ==1:
            return n[0]
        elif len(n)==0:
            return 130   
        elif len(n) > 1:
            return 132
        
    else:
        return 26
    

def mp_to_bet_add_game_id_no_VH(df_mp_teams, mp_date, nhl_name):##put VH in there! duh
    ha = df_mp_teams.loc[(df_mp_teams['mp_date'] == mp_date)&(df_mp_teams['nhl_name'] == nhl_name),  :]['game_id'].values
    if len(ha) ==1:
        return ha[0]
    elif len(ha)==0: 
        return 180   
    elif len(ha) > 1:
        return 182
    else:
        return 26

In [5]:
##? not sure what this is ... 
from numpy.core.numeric import True_

import pandas as pd
import numpy as np

##skip import lines because we are in notebook ... so those files with functions are copied above

## this function gives detailed info on NaN values of input df
#from data_clean import perc_null

#these functionas add a date column (x2) and correct mp season format

#from data_fix_dates import game_add_mp_date, bet_add_mp_date,  fix_mp_season 

#these functions assign nhl_names eg 'NYR' to bet, mp, and game; 
# functions use simple dictionaries

#from data_fix_team_names import bet_to_nhl, mp_to_nhl, game_to_nhl

##these are two different functions for assigning game_id to df_betting, based on team, date, H/A
##one uses df_game as look up table ... other uses df_mp_teams as look up table

#from data_bet_add_game_id import mp_to_bet_add_game_id, game_to_bet_add_game_id


##import all the files 

##file paths

Kaggle_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/"
mp_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/"
betting_path = "/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/"
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Betting_Data/nhl odds 2007-08.xlsx
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Kaggle_Data_Ellis/
#data_bootcamp/GitHub/final_project_nhl_prediction/Data/Money_Puck_Data/


##Kaggle files

df_game = pd.read_csv(Kaggle_path+'game.csv')
df_game_team_stats = pd.read_csv(Kaggle_path+'game_teams_stats.csv')
df_game_skater_stats = pd.read_csv(Kaggle_path+'game_skater_stats.csv')
df_game_goalie_stats = pd.read_csv(Kaggle_path+'game_goalie_stats.csv')

##more subtle Kaggle features:
df_game_scratches = pd.read_csv(Kaggle_path+'game_scratches.csv')
df_game_officials = pd.read_csv(Kaggle_path+'game_officials.csv')
df_team_info = pd.read_csv(Kaggle_path+'team_info.csv')

## grab all the moneypuck data 

df_mp_teams = pd.read_csv(mp_path+'all_teams.csv')


## grab all betting data 
df1 = pd.read_excel(io = betting_path+'nhl odds 2007-08.xlsx')
df2 = pd.read_excel(io = betting_path+'nhl odds 2008-09.xlsx')
df3 = pd.read_excel(io = betting_path+'nhl odds 2009-10.xlsx')
df4 = pd.read_excel(io = betting_path+'nhl odds 2010-11.xlsx')
df5 = pd.read_excel(io = betting_path+'nhl odds 2011-12.xlsx')
df6 = pd.read_excel(io = betting_path+'nhl odds 2012-13.xlsx')
df7 = pd.read_excel(io = betting_path+'nhl odds 2013-14.xlsx')
df8 = pd.read_excel(io = betting_path+'nhl odds 2014-15.xlsx')
df9 = pd.read_excel(io = betting_path+'nhl odds 2015-16.xlsx')
df10 = pd.read_excel(io = betting_path+'nhl odds 2016-17.xlsx')
df11 = pd.read_excel(io = betting_path+'nhl odds 2017-18.xlsx')
df12 = pd.read_excel(io = betting_path+'nhl odds 2018-19.xlsx')
df13 = pd.read_excel(io = betting_path+'nhl odds 2019-20.xlsx')




df1['season'] = 20072008
df2['season'] = 20082009
df3['season'] = 20092010
df4['season'] = 20102011
df5['season'] = 20112012
df6['season'] = 20122013
df7['season'] = 20132014
df8['season'] = 20142015
df9['season'] = 20152016
df10['season'] = 20162017
df11['season'] = 20172018
df12['season'] = 20182019
df13['season'] = 20192020

##omit 20072008 
df_betting = pd.concat([df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13])

In [6]:
df_mp_teams

,team,season,name,gameId,playerTeam,opposingTeam,home_or_away,gameDate,position,situation,...,unblockedShotAttemptsAgainst,scoreAdjustedUnblockedShotAttemptsAgainst,dZoneGiveawaysAgainst,xGoalsFromxReboundsOfShotsAgainst,xGoalsFromActualReboundsOfShotsAgainst,reboundxGoalsAgainst,totalShotCreditAgainst,scoreAdjustedTotalShotCreditAgainst,scoreFlurryAdjustedTotalShotCreditAgainst,playoffGame
0,NYR,2008,NYR,2008020001,NYR,T.B,AWAY,20081004,Team Level,other,...,1.0,1.000,0.0,0.017,0.000,0.000,0.037,0.037,0.037,0
1,NYR,2008,NYR,2008020001,NYR,T.B,AWAY,20081004,Team Level,all,...,31.0,30.369,5.0,0.396,0.168,0.168,2.917,2.833,2.714,0
2,NYR,2008,NYR,2008020001,NYR,T.B,AWAY,20081004,Team Level,5on5,...,20.0,19.369,3.0,0.237,0.168,0.168,1.862,1.777,1.665,0
3,NYR,2008,NYR,2008020001,NYR,T.B,AWAY,20081004,Team Level,4on5,...,9.0,9.000,1.0,0.124,0.000,0.000,0.795,0.795,0.789,0
4,NYR,2008,NYR,2008020001,NYR,T.B,AWAY,20081004,Team Level,5on4,...,1.0,1.000,1.0,0.019,0.000,0.000,0.224,0.224,0.224,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161445,L.A,2017,L.A,2017030174,L.A,VGK,HOME,20180417,Team Level,other,...,0.0,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,1
161446,L.A,2017,L.A,2017030174,L.A,VGK,HOME,20180417,Team Level,all,...,34.0,36.654,8.0,0.320,0.285,0.285,1.853,2.012,1.976,1
161447,L.A,2017,L.A,2017030174,L.A,VGK,HOME,20180417,Team Level,5on5,...,32.0,34.654,7.0,0.299,0.285,0.285,1.814,1.972,1.937,1
161448,L.A,2017,L.A,2017030174,L.A,VGK,HOME,20180417,Team Level,4on5,...,2.0,2.000,0.0,0.021,0.000,0.000,0.040,0.040,0.040,1
161449,L.A,2017,L.A,2017030174,L.A,VGK,HOME,20180417,Team Level,5on4,...,0.0,0.000,1.0,0.000,0.000,0.000,0.000,0.000,0.000,1

In [7]:

### set up list of all the df's for easy for loops
data_frames_all = [df_mp_teams, 
df_betting,
df_game,
df_game_team_stats, 
df_game_goalie_stats,
df_team_info,
df_game_officials,
df_game_scratches, 
df_game_skater_stats]

##for now just worry about joining these ones:

data_frames = [df_mp_teams, df_betting, df_game_team_stats]

In [8]:
df_game_team_stats.shape #before droping duplicates

(52610, 17)

In [9]:


df_betting = df_betting.loc[:, ['Date', 'season','VH', 'Team', 'Open']].copy()
df_mp_teams.rename(columns={"teamId": "team_id", 'gameDate': 'mp_date', 'gameId':'game_id' }, inplace = True)
##note there are other column names which differ, but team_id, mp_date, game_id are key for joining so we  
##make it consistent

df_mp_teams_big = df_mp_teams.copy()
##only has the rows for all situations (divide num rows by 5)
df_mp_teams = df_mp_teams.loc[(df_mp_teams['situation'] == 'all'), :] #&(df_mp_teams['playoffGame']==0), :].copy()

##restrict types to all situations later before merge 

df_game_team_stats.drop_duplicates(inplace = True)
df_game_team_stats = df_game_team_stats[~df_game_team_stats['team_id'].isin([87,88,89,90])].copy()
df_betting = df_betting[~(df_betting['VH'] == 'N')].copy()

In [10]:
df_game_team_stats.shape

(47460, 17)

In [11]:


df_mp_teams.loc[:,'season'] = np.vectorize(fix_mp_season)(df_mp_teams.loc[:,'season'])


##restrict seasons; 
seasons = []
for n in range(2008,2020):
    seasons.append(int(str(n)+str(n+1)))

#check seasons look ok
print(seasons)

[20082009, 20092010, 20102011, 20112012, 20122013, 20132014, 20142015, 20152016, 20162017, 20172018, 20182019, 20192020]

/Users/joejohns/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [12]:
df_mp_teams['season'].value_counts()

20182019    2716
20172018    2710
20132014    2646
20152016    2642
20142015    2638
20092010    2636
20102011    2636
20162017    2634
20112012    2632
20082009    2628
20192020    2424
20202021    1736
20122013    1612
Name: season, dtype: int64

In [13]:


df_betting = df_betting.loc[df_betting['season'].isin(seasons), :].copy()
#df_game_team_stats = df_game_team_stats.loc[df_game_team_stats['season'].isin(seasons), :].copy()
df_mp_teams = df_mp_teams.loc[df_mp_teams['season'].isin(seasons), :].copy()
#df_mp_teams = df_mp_teams.loc[df_mp_teams['season'].isin(seasons), :].copy()


## the index is no longer consecutive so we reset:

df_betting.reset_index(drop = True, inplace = True)
#df_game_team_stats.reset_index(drop = True, inplace = True)
df_mp_teams.reset_index(drop = True, inplace = True)


##! restrict df_game_team_stats later using the game_id

In [14]:
df_betting.shape

(30300, 5)

In [15]:
df_betting['mp_date'] = np.vectorize(bet_add_mp_date)(df_betting['Date'], df_betting['season'])

HA_dic = { 'H': 'home', 'V': 'away', 'HOME': 'home', 'AWAY':'away'}
def add_HoA(h_or_a):  # h_or_a can be either of the formats used by mp or betting
    return HA_dic[h_or_a]

df_betting['HoA'] = df_betting['VH'].apply(add_HoA)

df_mp_teams['HoA'] = df_mp_teams['home_or_away'].apply(add_HoA)




df_betting['nhl_name'] = df_betting['Team'].apply(bet_to_nhl)
df_game_team_stats['nhl_name'] = df_game_team_stats['team_id'].apply(game_to_nhl)
df_mp_teams['nhl_name'] = df_mp_teams['name'].apply(mp_to_nhl)

df_betting['game_id'] =  np.vectorize(mp_to_bet_add_game_id_no_VH, excluded={0})(df_mp_teams, df_betting['mp_date'], df_betting['nhl_name'] )

In [17]:
list_df =[df_mp_teams, df_betting, df_game_team_stats]

common_game_ids = set.intersection( set(list_df[0]['game_id']) , set(list_df[1]['game_id']) , set(list_df[2]['game_id'])   ) 



df_betting = df_betting.loc[df_betting['game_id'].isin(common_game_ids), :].copy()
df_game_team_stats = df_game_team_stats.loc[df_game_team_stats['game_id'].isin(common_game_ids), :].copy()
df_mp_teams = df_mp_teams.loc[df_mp_teams['game_id'].isin(common_game_ids), :].copy()

In [18]:
##check consistency of nhl_names, HoA ...

df_mp_teams.sort_values(by = ['game_id', 'nhl_name'], inplace = True)
df_game_team_stats.sort_values(by = ['game_id', 'nhl_name'], inplace = True)
df_betting.sort_values(by = ['game_id', 'nhl_name'], inplace = True)

df_betting.reset_index(drop = True, inplace = True)
df_game_team_stats.reset_index(drop = True, inplace = True)
df_mp_teams.reset_index(drop = True, inplace = True)

In [84]:
df_game.loc[df_game['game_id'] == 2012020159,:]

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
6415,2012020159,20122013,R,2013-02-09T21:00:00Z,27,28,1,0,away win OT,left,HP Pavilion at San Jose,/api/v1/venues/null,America/Los_Angeles,-7,PDT

In [97]:
df_game_team_stats.groupby('game_id')['goals'].sum().loc[(df_game_team_stats.groupby('game_id')['goals'].sum()==0)].index

Int64Index([2008020057, 2008020071, 2008020306, 2008020623, 2008021108,
            2008021196, 2009020072, 2009020253, 2009020682, 2009020831,
            2009021118, 2009021209, 2010020382, 2010020761, 2010020878,
            2010021111, 2011020749, 2011020787, 2011021016, 2011021052,
            2011021108, 2012020159, 2012020412, 2012020487, 2013020126,
            2013021136, 2013021223, 2014020055, 2014020158, 2014020313,
            2014020456, 2014021008, 2014021210, 2016020785, 2017020561,
            2017020965, 2018020783, 2019020127, 2019021041],
           dtype='int64', name='game_id')

In [115]:
num_goals = df_game_team_stats.groupby('game_id')['goals'].sum()
bag_game_ids = list(num_goals[num_goals ==0])

In [103]:
df_game.loc[df_game['game_id'].isin(bad_game_ids),:]

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
1355,2017020561,20172018,R,2017-12-28T01:00:00Z,15,3,0,1,home win OT,right,Madison Square Garden,/api/v1/venues/null,America/New_York,-4,EDT
2343,2016020785,20162017,R,2017-02-05T18:00:00Z,22,8,1,0,away win OT,right,Centre Bell,/api/v1/venues/null,America/Montreal,-4,EDT
3658,2017020965,20172018,R,2018-02-27T00:30:00Z,4,8,1,0,away win OT,right,Centre Bell,/api/v1/venues/null,America/Montreal,-4,EDT
4260,2014020055,20142015,R,2014-10-17T02:30:00Z,19,26,0,1,home win OT,right,STAPLES Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT
4323,2014021210,20142015,R,2015-04-10T01:00:00Z,52,21,0,1,home win OT,right,Pepsi Center,/api/v1/venues/null,America/Denver,-6,MDT
4345,2014020456,20142015,R,2014-12-17T00:30:00Z,29,17,1,0,away win OT,right,Joe Louis Arena,/api/v1/venues/null,America/Detroit,-4,EDT
4447,2014020313,20142015,R,2014-11-25T00:00:00Z,4,2,0,1,home win OT,left,Nassau Coliseum,/api/v1/venues/null,America/New_York,-4,EDT
4567,2014020158,20142015,R,2014-11-01T23:00:00Z,52,3,1,0,away win OT,right,Madison Square Garden,/api/v1/venues/null,America/New_York,-4,EDT
4654,2014021008,20142015,R,2015-03-13T00:00:00Z,4,19,0,1,home win OT,left,Scottrade Center,/api/v1/venues/null,America/Chicago,-5,CDT
5323,2013021223,20132014,R,2014-04-13T19:00:00Z,14,15,1,0,away win OT,right,Verizon Center,/api/v1/venues/null,America/New_York,-4,EDT
5597,2013020126,20132014,R,2013-10-21T23:30:00Z,28,17,1,0,away win OT,right,Joe Louis Arena,/api/v1/venues/null,America/Detroit,-4,EDT
5696,2013021136,20132014,R,2014-04-02T00:00:00Z,4,19,0,1,home win OT,left,Scottrade Center,/api/v1/venues/null,America/Chicago,-5,CDT
6111,2012020412,20122013,R,2013-03-16T23:00:00Z,27,29,0,1,home win OT,left,Nationwide Arena,/api/v1/venues/null,America/New_York,-4,EDT
6415,2012020159,20122013,R,2013-02-09T21:00:00Z,27,28,1,0,away win OT,left,HP Pavilion at San Jose,/api/v1/venues/null,America/Los_Angeles,-7,PDT
6738,2012020487,20122013,R,2013-03-27T02:00:00Z,29,23,0,1,home win OT,right,Rogers Arena,/api/v1/venues/null,America/Vancouver,-7,PDT
7054,2010020761,20102011,R,2011-02-02T01:00:00Z,26,30,0,1,home win OT,right,Xcel Energy Center,/api/v1/venues/null,America/Chicago,-5,CDT
7471,2011021052,20112012,R,2012-03-15T23:00:00Z,21,1,0,1,home win OT,left,Prudential Center,/api/v1/venues/null,America/New_York,-4,EDT
7776,2011020749,20112012,R,2012-02-02T00:30:00Z,3,7,1,0,away win OT,left,First Niagara Center,/api/v1/venues/null,America/New_York,-4,EDT
7844,2010020878,20102011,R,2011-02-20T00:00:00Z,9,10,1,0,away win OT,right,Air Canada Centre,/api/v1/venues/null,America/Toronto,-4,EDT
8135,2011021108,20112012,R,2012-03-23T02:30:00Z,19,26,0,1,home win OT,right,Staples Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT
8209,2011021016,20112012,R,2012-03-11T00:00:00Z,4,10,1,0,away win OT,right,Air Canada Centre,/api/v1/venues/null,America/Toronto,-4,EDT
8430,2010021111,20102011,R,2011-03-25T23:00:00Z,1,5,0,1,home win OT,left,CONSOL Energy Center,/api/v1/venues/null,America/New_York,-4,EDT
8468,2010020382,20102011,R,2010-12-05T00:00:00Z,7,9,1,0,away win OT,left,Scotiabank Place,/api/v1/venues/null,America/New_York,-4,EDT
8695,2011020787,20112012,R,2012-02-08T00:00:00Z,2,4,1,0,away win OT,right,Wells Fargo Center,/api/v1/venues/null,America/New_York,-4,EDT
9290,2009020253,20092010,R,2009-11-13T00:00:00Z,13,6,1,0,away win OT,left,TD Garden,/api/v1/venues/null,America/New_York,-4,EDT
9531,2009021118,20092010,R,2010-03-28T00:00:00Z,17,18,1,0,away win OT,left,Bridgestone Arena,/api/v1/venues/null,America/Chicago,-5,CDT
9636,2009020682,20092010,R,2010-01-13T00:00:00Z,1,3,1,0,away win OT,right,Madison Square Garden,/api/v1/venues/null,America/New_York,-4,EDT
9854,2009021209,20092010,R,2010-04-09T23:00:00Z,17,29,1,0,away win OT,left,Nationwide Arena,/api/v1/venues/null,America/New_York,-4,EDT
9962,2009020072,20092010,R,2009-10-13T02:30:00Z,27,28,1,0,away win OT,left,HP Pavilion at San Jose,/api/v1/venues/null,America/Los_Angeles,-7,PDT
10276,2009020831,20092010,R,2010-02-03T01:00:00Z,27,18,1,0,away win OT,left,Sommet Center,/api/v1/venues/null,America/Chicago,-5,CDT
10614,2008020623,20082009,R,2009-01-11T02:00:00Z,25,27,0,1,home win OT,NaN,Jobing.com Arena,/api/v1/venues/null,America/Phoenix,-7,MST
10872,2008021108,20082009,R,2009-03-27T00:30:00Z,26,25,1,0,away win OT,right,American Airlines Center,/api/v1/venues/null,America/Chicago,-5,CDT
10899,2008020071,20082009,R,2008-10-18T23:30:00Z,30,14,1,0,away win OT,left,St. Pete Times Forum,/api/v1/venues/null,America/New_York,-4,EDT
11222,2008021196,20082009,R,2009-04-08T02:30:00Z,21,28,0,1,home win OT,left,HP Pavilion at San Jose,/api/v1/venues/null,America/Los_Angeles,-7,PDT
11361,2008020306,20082009,R,2008-11-26T00:00:00Z,19,18,1,0,away win OT,left,Sommet Center,/api/v1/venues/null,America/Chicago,-5,CDT
11776,2008020057,20082009,R,2008-10-17T23:00:00Z,10,3,0,1,home win OT,right,Madison Square Garden,/api/v1/venues/null,America/New_York,-4,EDT
21409,2019020127,20192020,R,2019-10-20T23:00:00Z,22,52,0,1,home win OT,right,Bell MTS Place,/api/v1/venues/5058,America/Winnipeg,-5,CDT
21414,2019020127,20192020,R,2019-10-20T23:00:00Z,22,52,0,1,home win OT,right,Bell MTS Place,/api/v1/venues/5058,America/Winnipeg,-5,CDT
23236,2019021041,20192020,R,2020-03-06T03:30:00Z,10,26,0,1,home win OT,right,STAPLES Center,/api/v1/venues/5081,America/Los_Angeles,-8,PST
23246,2019021041,20192020,R,2020-03-06T03:30:00Z,10,26,0,1,home win OT,right,STAPLES Center,/api/v1/venues/5081,America/Los_Angeles,-8,PST
25151,2018020783,20182019,R,2019-02-02T00:00:00Z,14,2,1,0,away win OT,left,NYCB Live/Nassau Coliseum,/api/v1/venues/null,America/New_York,-5,EST
25159,2018020783,20182019,R,2019-02-02T00:00:00Z,14,2,1,0,away win OT,left,NYCB Live/Nassau Coliseum,/api/v1/venues/null,America/New_York,-5,EST

In [102]:
(df_game_team_stats.groupby('game_id')['goals'].sum()==0).sum()
#df_game_team_stats.loc[ 'game_id']

39

In [81]:
df_game_team_stats.loc[df_game_team_stats['game_id'] == 2012020159, :]

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide,nhl_name
10492,2012020159,27,away,True,OT,Dave Tippett,0.0,21.0,17.0,8.0,3.0,0.0,54.7,14.0,11.0,22.0,right,ARI
10493,2012020159,28,home,False,OT,Todd McLellan,0.0,33.0,14.0,6.0,4.0,0.0,45.3,20.0,6.0,11.0,right,SJS

In [40]:
X_merge = pd.merge(df_betting, df_game_team_stats, on = ['game_id', 'nhl_name'], how = 'inner', suffixes = ('_bet', '_gm_stats'))

X_merge2 = pd.merge(X_merge, df_mp_teams, on = ['game_id', 'nhl_name', 'mp_date', 'season'], how = 'inner', suffixes = ('_merge', '_mp_teams'))

print(2*len(common_game_ids),
      X_merge2.shape[0])

In [43]:
def find_discrep(col):
    A = (df_mp_teams[col] != df_game_team_stats[col])
    B = (df_mp_teams[col] != df_betting[col])
    C = (df_game_team_stats[col] != df_betting[col])
    
    A_mp = df_mp_teams.loc[ A|B|C, ['game_id', 'nhl_name', col, 'season' ]  ]
    A_bet = df_betting.loc[ A|B|C, ['game_id', 'nhl_name', col ]  ]
    A_stats = df_game_team_stats.loc[ A|B|C, ['game_id', 'nhl_name', col  ]  ]

    A_all = pd.concat([A_mp, A_bet, A_stats], axis = 1)
    return (A_all, (len(A), len(B), len(C)))
    #A_all.iloc[:, :].shape   ##not too many wrong labels ...

In [51]:
find_discrep('HoA')#.iloc[0:30,:]

,game_id,nhl_name,HoA,season,game_id,nhl_name,HoA,game_id,nhl_name,HoA
2468,2009020008,DET,home,20092010,2009020008,DET,away,2009020008,DET,home
2469,2009020008,STL,away,20092010,2009020008,STL,home,2009020008,STL,away
2492,2009020020,DET,away,20092010,2009020020,DET,home,2009020020,DET,away
2493,2009020020,STL,home,20092010,2009020020,STL,away,2009020020,STL,home
4920,2010020006,CBJ,home,20102011,2010020006,CBJ,away,2010020006,CBJ,home
...,...,...,...,...,...,...,...,...,...,...
14246,2013021230,ARI,away,20132014,2013021230,ARI,home,2013021230,ARI,home
23548,2017020601,BUF,home,20172018,2017020601,BUF,away,2017020601,BUF,home
23549,2017020601,NYR,away,20172018,2017020601,NYR,home,2017020601,NYR,away
29252,2019020740,DET,home,20192020,2019020740,DET,away,2019020740,DET,home
29253,2019020740,PIT,away,20192020,2019020740,PIT,home,2019020740,PIT,away

In [68]:
A = (df_mp_teams['HoA'] != df_game_team_stats['HoA'])
B = (df_mp_teams['HoA'] != df_betting['HoA'])
C = (df_game_team_stats['HoA'] != df_betting['HoA'])

A_mp = df_mp_teams.loc[ C, ['mp_date','game_id', 'nhl_name', 'HoA', 'season' ]  ]
A_bet = df_betting.loc[ C, ['game_id', 'nhl_name', 'HoA' ,'Open']  ]
A_stats = df_game_team_stats.loc[C, ['game_id', 'nhl_name', 'HoA'  ]  ]

A_all = pd.concat([A_mp, A_bet, A_stats], axis = 1)
A_all.iloc[:, :]   ##not too many wrong labels ... ##ha ... all these games have outrageous favorites anyway ...

,mp_date,game_id,nhl_name,HoA,season,game_id,nhl_name,HoA,Open,game_id,nhl_name,HoA
2468,20091002,2009020008,DET,home,20092010,2009020008,DET,away,-133,2009020008,DET,home
2469,20091002,2009020008,STL,away,20092010,2009020008,STL,home,113,2009020008,STL,away
2492,20091003,2009020020,DET,away,20092010,2009020020,DET,home,-166,2009020020,DET,away
2493,20091003,2009020020,STL,home,20092010,2009020020,STL,away,146,2009020020,STL,home
4920,20101008,2010020006,CBJ,home,20102011,2010020006,CBJ,away,165,2010020006,CBJ,home
4921,20101008,2010020006,SJS,away,20102011,2010020006,SJS,home,-185,2010020006,SJS,away
4952,20101009,2010020022,CBJ,away,20102011,2010020022,CBJ,home,142,2010020022,CBJ,away
4953,20101009,2010020022,SJS,home,20102011,2010020022,SJS,away,-162,2010020022,SJS,home
23548,20180101,2017020601,BUF,home,20172018,2017020601,BUF,away,155,2017020601,BUF,home
23549,20180101,2017020601,NYR,away,20172018,2017020601,NYR,home,-175,2017020601,NYR,away
29252,20200117,2019020740,DET,home,20192020,2019020740,DET,away,192,2019020740,DET,home
29253,20200117,2019020740,PIT,away,20192020,2019020740,PIT,home,-230,2019020740,PIT,away

In [56]:
print(A.sum(), B.sum(), C.sum())

115 127 12

In [41]:
list_small = [cols for cols in list(X_merge2.columns) if '_' in cols]
sorted(list_small)

['HoA_bet',
 'HoA_gm_stats',
 'game_id',
 'head_coach',
 'home_or_away',
 'mp_date',
 'nhl_name',
 'settled_in',
 'team_id']

In [46]:
data_bet_stats_mp1 = X_merge2.copy()
data_bet_stats_mp1.to_csv('/Users/joejohns/data_bootcamp/GitHub/final_project_nhl_prediction/Data/Shaped_Data/data_bet_stats_mp.csv')

In [64]:
df_betting.loc[(df_betting['mp_date'] == 20200117), :]

,Date,season,VH,Team,Open,mp_date,HoA,nhl_name,game_id
29252,117,20192020,V,Detroit,192,20200117,away,DET,2019020740
29253,117,20192020,H,Pittsburgh,-230,20200117,home,PIT,2019020740
29254,117,20192020,V,Anaheim,202,20200117,away,ANA,2019020741
29255,117,20192020,H,Carolina,-244,20200117,home,CAR,2019020741
29256,117,20192020,V,TampaBay,-140,20200117,away,TBL,2019020742
29257,117,20192020,H,Winnipeg,120,20200117,home,WPG,2019020742

In [66]:
(X_merge2['HoA'] == df_mp_teams['HoA']).sum()

29938

In [67]:
X_merge2.shape

(29938, 134)

In [80]:
df_mp_teams.loc[:20, ['blockedShotAttemptsAgainst', 'blockedShotAttemptsFor', 'freezeFor', 'xFreezeFor', 'freezeAgainst','xFreezeAgainst',]]

,blockedShotAttemptsAgainst,blockedShotAttemptsFor,freezeFor,xFreezeFor,freezeAgainst,xFreezeAgainst
0,6.0,13.0,14.0,8.155,5.0,4.436
1,13.0,6.0,5.0,4.436,14.0,8.155
2,21.0,11.0,6.0,8.056,4.0,6.946
3,11.0,21.0,4.0,6.946,6.0,8.056
4,12.0,20.0,3.0,9.068,4.0,5.124
5,20.0,12.0,4.0,5.124,3.0,9.068
6,14.0,15.0,5.0,6.771,3.0,5.631
7,15.0,14.0,3.0,5.631,5.0,6.771
8,9.0,11.0,8.0,8.083,9.0,5.442
9,11.0,9.0,9.0,5.442,8.0,8.083
10,22.0,10.0,3.0,3.948,9.0,7.506
11,10.0,22.0,9.0,7.506,3.0,3.948
12,11.0,15.0,7.0,5.836,8.0,5.295
13,15.0,11.0,8.0,5.295,7.0,5.836
14,15.0,10.0,10.0,4.608,6.0,7.565
15,10.0,15.0,6.0,7.565,10.0,4.608
16,8.0,16.0,8.0,7.065,4.0,5.247
17,16.0,8.0,4.0,5.247,8.0,7.065
18,12.0,8.0,8.0,7.054,9.0,6.208
19,8.0,12.0,9.0,6.208,8.0,7.054
20,24.0,16.0,4.0,5.941,3.0,8.514

In [71]:
df_game_team_stats.loc[0:20, 'blocked']

0      6.0
1     13.0
2     21.0
3     11.0
4     12.0
5     20.0
6     14.0
7     15.0
8      9.0
9     11.0
10    22.0
11    10.0
12    11.0
13    15.0
14    15.0
15    10.0
16     8.0
17    16.0
18    12.0
19     8.0
20    24.0
Name: blocked, dtype: float64